### PR TITLE
Feat monitor fixes

### LINKED ISSUE #48: Monitor usage in `QUICConnection`
### Specification

The monitor is necessary to enable re-entrancy within a call graph of certain operations like `send` and `recv` in `QUICConnection` while also ensuring mutual exclusion between different call graphs.

However, the `monitor` currently as used isn't using the `monitor` resource acquisition function that I had earlier created in https://github.com/MatrixAI/js-contexts/pull/2.

I just pushed out `1.2.0` of `js-contexts` which exposes `monitor` as a `ResourceAcquire`.

You can remove the `utils.withMonitor` in favour of doing something like this:

```ts
await withF(monitor(this.lockBox, RWLockWriter), async ([mon]) => {
  await x.f({ monitor: mon });
});
```

Additionally in the beginning during `QUICConnection.createQUICConnection`, you don't actually need to setup so much just to do the initial `recv` and `send` under after `start`.

Also you don't need to lock anything in that scenario cause nothing is actually going to be able to intercept those calls during `createQUICConnection` because nothing else has reference to the `QUICConnection` instance.

I think it would far more clearer to write it in a way where your initial `recv` and `send` is just part of the `async start` method. Just put your `recv` and `send` calls within that. It does not appear that `start` is called anywhere else, so it can just be part of `QUICConnection.start`.

Finally both `send` and `recv` should have `mon?: Monitor`. Both should then use the `withF` pattern above in case the monitor doesn't yet exist.

### Additional context

* https://github.com/MatrixAI/js-quic/commit/cbedc265c7d9d4e490f3b02c3f7d8d3e9fb54fc5#r125026883

### Tasks

1. Use `1.2.0` of `js-contexts` to get access to the `monitor` function.
2. Replace `utils.withMonitor` with `monitor`
3. Use `withF` pattern to create monitor for both `send` and `recv`
4. Incorporate initial `recv` and `send` within `QUICConnection.start`, since that would be much clearer. You can still setup a monitor, but no locking is really required at that point.
5. In the `QUICServer`, why is there an additional separation of `connectionProm`? This is unnecessary.

### PR DESCRIPTION
**Pull request by tegefaulkes**
### Description

This PR addresses some small issues in the `js-quic` code.

As per discussion, the constraint on the connection start timeout should be removed. During usage we can set this to whatever without the context of the idle timeout being know. In that case it's very likely to throw an error.  We'll allow any value to be valid with the caveat that a lower idle timeout will supersede the startup timeout.

During review we found that server type connections startup timeout defaults to infinity. creation here depends on establishment and secure events so it's possible for a server connection to be stuck in limbo if these events are never reached. A default start timeout should be applied here. 

### Issues Fixed

* Fixes #48 

### Tasks

- [x] 1. Address issue #48 
- [ ] 2. Apply startup timeout to a server connection getting created
- [ ] 3. Remove constraint between start timeout and max idle timeout values. A longer startup timeout will be allowed but superseded by the idle timeout.

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Also move the recv and send into the start method of `QUICConnection`.

File: src/utils.ts
Comment (CMCDragonkai) [inline src/utils.ts:1]: I think you don't need this withMonitor utility? Just use `withF` directly.

Comment (tegefaulkes) [reply src/utils.ts:1]: I'm keeping the utility as a neater way to create the monitor if it didn't already exist.

**Comment by tegefaulkes** [comment]
as per task 2. we need a startup timeout for server connections. This is for the connection to establish and secure before it's fully created as a `QUICConnection`. This needs to be a new option for the QUICServer to set and have a default. 

I'm not sure what to call this new option. `ConnectionEstablishTimeoutTime`, `ConnectionCreationTimeoutTime`, ConnectionStartTimeoutTime`, `nodesConnectionConnectTime`?

What's a reasonable default here? Technically the connection is already created so we're just waiting for some negotiation. So 1-2 seconds is more than enough?

**Comment by CMCDragonkai** [comment]
No I already specced this out earlier in the configuration entropy issue.

```
connectTimeoutTime
keepAliveTimeoutTime
keepAliveIntervalTime
```

**Comment by CMCDragonkai** [comment]
Again defaults based what I talked about yesterday.

15 seconds for connect, 30 seconds for keep alive, 10 seconds for interval.

Make this consistent everybody. Already in my PR.

File: src/QUICConnection.ts
Comment (CMCDragonkai) [inline src/QUICConnection.ts:1]: Hey you need to check if it is server connection before doing the initial recv and send. I think you forgot the condition.

File: src/QUICConnection.ts [hunk 1]
```diff
@@ -471,12 +461,24 @@ class QUICConnection extends EventTarget {
...
+  public async start(initialData?: {
+    data: Uint8Array;
+    remoteInfo: RemoteInfo;
+  }): Promise<void> {
     this.logger.info(`Start ${this.constructor.name}`);
     // Set the connection up
     this.socket.connectionMap.set(this.connectionId, this);
-    await this.send();
+    await withF(
+      [contextsUtils.monitor(this.lockbox, RWLockWriter)],
```
Comment (CMCDragonkai) [inline src/QUICConnection.ts:474]: You're already using `withF` here. So why not continue using it instead of the custom utility? Or vice versa?

Comment (CMCDragonkai) [reply src/QUICConnection.ts:474]: Don't use `initialData` you're basing this on a server type originally. I think it should be made clear that it is done only on server.

File: src/utils.ts [hunk 2]
```diff
@@ -464,17 +466,26 @@ function streamStats(
...
   lockBox: LockBox<RWLockWriter>,
   lockConstructor: { new (): RWLockWriter },
   fun: (mon: Monitor<RWLockWriter>) => Promise<T>,
   locksPending?: Map<string, { count: number }>,
 ): Promise<T> {
-  const _mon = mon ?? new Monitor(lockBox, lockConstructor, locksPending);
-  const result = await fun(_mon);
-  if (mon != null) await _mon.unlockAll();
-  return result;
+  if (mon == null) {
```
Comment (CMCDragonkai) [inline src/utils.ts:479]: The `fun` should be `f`, be consistent.

File: src/utils.ts [hunk 3]
```diff
@@ -464,17 +466,26 @@ function streamStats(
...
+    return await withF(
+      [contextsUtils.monitor(lockBox, lockConstructor, locksPending)],
+      async ([mon]) => {
+        return await fun(mon);
```
Comment (CMCDragonkai) [inline src/utils.ts:483]: No need to return an `await`.

File: src/utils.ts [hunk 4]
```diff
@@ -464,17 +466,26 @@ function streamStats(
...
+      },
+    );
+  } else {
+    return await fun(mon);
```
Comment (CMCDragonkai) [inline src/utils.ts:487]: No need to return an `await`.

File: src/utils.ts
Comment (CMCDragonkai) [reply src/utils.ts:1]: If you do this, make it a method of the `QUICConnection`.

File: src/QUICConnection.ts
Comment (tegefaulkes) [reply src/QUICConnection.ts:1]: No, that's being done, the `recv` is only done if the `initialData` is provided. We only provide the `inititalData` to start if it was a server connection.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1]: As I said below, the idea of initial data... Is that really any different from classifying this behaviour between client and server? I feel like classifying based on server type is more obvious than the presence of initial data. This smells like boolean blindness. But in this case it's a swap from a high level classifier to a low level classifier with no increase in understanding. One could document that server type means there's initial data, and I prefer the top down explanation.

File: src/QUICConnection.ts (hunk 1 above)
Comment (tegefaulkes) [reply src/QUICConnection.ts:468]: `withF` is used here because the monitor is always created here. The utility is used when the `mon` is optional and may need to be created and used. I would've inlined it but branching the monitor creation is a little annoying outside of a separate function.

Made clear as in use a comment? Make the `initialData` a property of the QUICConnection and check that? Throw an exception if the connection type isn't `server` and data is provided?

File: src/utils.ts (hunk 2 above)
Comment (tegefaulkes) [reply src/utils.ts:479]: Fixing, Also this block of code could've been a single review comment.

File: src/utils.ts (hunk 3 above)
Comment (tegefaulkes) [reply src/utils.ts:483]: fixed.

File: src/utils.ts (hunk 4 above)
Comment (tegefaulkes) [reply src/utils.ts:487]: fixed.

File: src/utils.ts (hunk 2 above)
Comment (tegefaulkes) [reply src/utils.ts:479]: Fixed.

File: src/utils.ts
Comment (tegefaulkes) [reply src/utils.ts:1]: I have moved it.

**Comment by tegefaulkes** [comment]
For reference 

<details>

```
# Polykey

* nodesConnectionConnectTimeoutTime: 15000,
* nodesConnectionKeepAliveTimeoutTime: 30000,
* nodesConnectionKeepAliveIntervalTime: 10000

## Client

QUICClient.createQUICClient(
  {
    config: {
      connectTimeoutTime: 15000,
      keepAliveTimeoutTime: 30000,
    }
  },
  {
    timer: 1000
  }
);

So quiche's `maxIdleTimeout` is encapsulated in our `js-quic`.

It also cannot be mutated.

It serves as both the connect timeout and the keep alive timeout for the underlying quiche connection.

In order to get the behaviour we want.

1. `maxIdleTimeout` would need to be set the maximum of `connectTimeoutTime` and `keepAliveTimeoutTime`.
2. The reason is because the `timer` is intended to mean how long I'm going to wait for the function to return, otherwise abort.
3. ? `timer <= connectTimeoutTime`
4. ? `connectTimeoutTime > keepAliveTimeoutTime` - Throw an error. This is not possible atm in js-quic.
5. If the `connectTimeoutTime <= keepAliveTimeoutTime` - We have to do a JS-level timer and abort.

Now let's change this up a bit.

config: {
  connectTimeoutTime: 15000,
  keepAliveTimeoutTime: 30000,
}

@timedCancellable(true, connectTimeoutTime, ...)
QUICClient.createQUICClient(
  {
    config: {
      keepAliveTimeoutTime: 30000, // this overrides the `keepAliveTimeoutTime`
    }
  },
  {
    timer: 1000 // this overrides the `connectTimeoutTime`
  }
);

1. Do we want connect timeout time to default to Infinity for both client and server? If so, then on `QUICClient`, you use `Infinity` for `@timedCancellable`, and secondly on `QUICServer` you just don't do anything.
   - Answer: This is moot. Because of the `maxIdleTimeout`. Unless you set the `maxIdleTimeout` to `0`, it's not possible to have an infinity server and client timeout.
2. The alternative is that both client and server have a default connect timeout of 15 seconds.


`connectTimeoutTime <= keepAliveTimeoutTime` is necessary.

But you cannot apply to the `timer`.

The end result is:

1. `keepAliveTimeoutTime` is the max boundary on both connect timeout and keep alive timeout
2. `timer` is the min boundary on only connec timeout

Because we aren't representing the true semantics of all of this

/**
 * Usually we would create separate timeouts for connecting vs idling.
 * Unfortunately quiche only has 1 config option that controls both.
 * And it is not possible to mutate this option after connecting.
 * Therefore, this option is just a way to set a shorter connecting timeout
 * compared to the idling timeout.
 * If this is the larger than the `maxIdleTimeout` (remember that `0` is `Infinity`) for `maxIdleTimeout`, then this has no effect.
 * This only has an effect if this is set to a number less than `maxIdleTimeout`.
 * Thus it is the "minimum boundary" of the timeout during connecting.
 * While the `maxIdleTimeout` is still the "maximum boundary" during connectin.
 */
const minIdleTimeout = Infinity,

export { minIdleTimeout };


config: {
  // Synthetic parameter, it is the minimum boundary, if this is greater than max idle timeout, it has no effect
  // It only has an effect if this is lower than the max idle timeout
  // On the client side it is the default for the timed cancellable decorator
  // On the server side, it is the default on `ctx.timer` when calling `QUICConnection.createQUICConnection`


  // This is the maximum boundary for connect timeout and keep alive timeout
  // Default to 0 to have a consistent defaults of "libraries" always using infinity
  maxIdleTimeout: 0,

  // Synthetic parameter (default undefined means no keep alive)
  keepAliveIntervalTime: undefined
}

@timedCancellable(true, minIdleTimeout, ...)
QUICClient.createQUICClient(
  {
    config: {
      maxIdleTimeout: 5000, // this overrides `maxIdleTimeout`
    }
  },
  {
    timer: 1000 // THIS IS THE MIN BOUNDARY
  }
);

## Server

Uses `Infinity` - which basically means the way it was before.

```
new QUICServer({ 
  config: {},
  minIdleTimeout
});
```

```
QUICConnection.createQUICConnection({}, { timer: minIdleTimeout })
```

Make sure the `QUICConnetion` is still defaulting to `Infinity`. No more constraints on `ctx.timer`.
```

</details>

**Comment by tegefaulkes** [comment]
Everything is addressed now. Waiting for the CI to finish to merge.

**Comment by CMCDragonkai** [comment]
Can you tick off tasks and the final checklist?
