### PR TITLE
Events Refactoring (integrating `js-events`)

### LINKED ISSUE #20: Streams not gracefully ending during high usage
### Specification

While working on #14 we discovered that during tests with a large amount of streams and data being sent concurrently. Readable streams would fail to end. So far as we could tell, random streams would fail to process a message from `streamRecv` that had `fin = true`. In these cases other streams would send a fin frame, end and clean up on both sides, all after the problematic stream should've done the same.

 Since then we found a stop-gap solution where we send a single null byte with the finish message. Given that, we're reasonably certain that the problem is related to 0-length messages not being sent or processed event though `fin` was set to true. 

Normally a 0-length message is not sent but in the case of a finish message they should be. This functionality was added in this commit https://github.com/cloudflare/quiche/commit/cc98af06cb1240fb1b1be3557166ca443b1d8653. 

Under normal conditions with low load. Sending fin frames with 0-length messages works fine. The problem only happens under higher loads during testing and even then, somewhat randomly. It's been hard to narrow down the specific conditions that cause the problem 

To address this problem multiple things need to be done.
1. Create a pure rust example that can reproduce the problem. This will be useful for the upstream issue
2. Investigate the `quiche` source code for the problem. based on what I understand is happening. The problem is likely located on the receiving side with marking the stream as readable after it has received the 0-length finish frame. But only during message loads.
3. Post an upstream issue with the rust example and a possible solution. Sooner the better so they can address the problem and fix it ASAP.

For now we're using a work-around where we add data to the fin frame message. In this case a single null byte. This should mark the stream as readable regardless of an potential issues with 0-length fin frames.

### Additional context

* Related #14 
* https://github.com/cloudflare/quiche/commit/cc98af06cb1240fb1b1be3557166ca443b1d8653

### Tasks

* [ ]  1. Create a pure rust example that can reproduce the problem. This will be useful for the upstream issue
* [ ]  2. Investigate the `quiche` source code for the problem. based on what I understand is happening. The problem is likely located on the receiving side with marking the stream as readable after it has received the 0-length finish frame. But only during message loads.
* [ ]  3. Post an upstream issue with the rust example and a possible solution. Sooner the better so they can address the problem and fix it ASAP.

### PR DESCRIPTION
**Pull request by CMCDragonkai**
### Description

https://github.com/MatrixAI/js-events provides a `Evented` decorator and `EventAny` that allows one to depend on all relevant of a given object.

This results in:

1. No longer single inheritance of `EventTarget`, instead we use a mixin.
2. Classes aren't supposed to extend `EventTarget` anyway
3. Encapsulated evented systems can have all their events listened for by just doing `addEventListener(callback)` without any type key string.
4. The declaration of events should now be `Event...` basically starting with an `Event` prefix similar to `Error...` prefix for errors.
5. The names of errors should statically checked by relying on the `EventClass.name` static property, rather than having to make up event names

Using events can be quite tricky, but we have come up with a general pattern.

1. `EventXError` - this is the general domain error event, all relevant exceptions will be part of the `detail` type.
2. `EventXClose` - this is a "close" event, the exact meaning depends on the construct. For example `QUICStream` has 2 separate close events for each side of the stream. On `QUICConnection` the close event handle has many duties because closing is an asynchronous concurrent process that involves draining whatever is still happening. The `detail` property will contain a subset of what is in the `detail` property of the error. This is because the error handler eats up some errors.
3. Each domain has their own handlers for both of those events as `handleEventXError` and `handleEventXClose`.
4. The error handler chain dispatches the close event.
5. The error handler will throw up any `ErrorXInternal` representing unrecoverable exceptions. This is expected to fail the program. Users can see it by assigning an uncaught exception handler. No close event is dispatched in this case.
6. The close handler will end up calling `stop` or `destroy`. But it does this intelligently, and just beforehand, it will resolve some promise indicating that closing is finished, that promise can be what the `stop` or `destroy` is waiting on.
7. When a user calls `stop` or `destroy`, this flow is separate from error -> close, instead the `stop` or `destroy` may proceed to dispatch close or error (even in case of graceful errors depending on the situation).
8. Some calls when hitting a "legitimate" error transition will dispatch the error event, but will continue. When hitting a non-legitimate error transition, will dispatch an internal error and then also throw up the error thus becoming a caller error.
9. In some cases, the close event can be dispatched independently, if a graceful close has nothing to do with an error event. In the case of `QUICConnection`, closing always involves an error even if the error code is `0` that's why graceful close is still an error event. But this is not necessarily true in other cases.
10. Encapsulated domains should have their events completely captured and redispatched upwards. This can be done with `EventAll` and `handleEventX` handlers. Injected domains should not have all their events completely captured and redispatched.
11. It is normal for parent domains to listen on child event domains.
12. Async things like this often have mutual calls, break up these mutual calls by identifying the dominant control flow origin (or origin of change), and have that be pull-based, while have the opposite flow be push-based. So you get a sort of pull-push hybrid. The primary advantage of this is to ensure that error handling is maintained within the relevant domain, instead of duplicating error handling logic. Sometimes this is not possible to break up, and you do need to duplicate it. In that case, consider factoring out the commonality if suitable, OR combine the 2 mutual parts into a single unit if suitable, and lacking all other options, duplicate the logic, but always identify the original (root) caller where the error handling happens, and where the buck has to stop otherwise resulting in uncaught exceptions (unless it is an unrecoverable error).
13. Unrecoverable errors can be implicit or explicit. An implicit unrecoverable error comes from calling a function that must succeed, and has no indication of throwing an error. An explicit unrecoverable error is where you call a function that may throw an exception, but it should not throw an exception except where there's a programmer error due to the logic, so you catch it and rethrow it upwards as an `ErrorXInternal`.

### Issues Fixed

* Related to https://github.com/MatrixAI/Polykey/pull/552
* Related https://github.com/MatrixAI/Polykey/issues/444
* Related https://github.com/MatrixAI/js-ws/pull/5
* Fixes #20 

### Tasks

- [x] 1. Replace all events with `Event...` prefixed class names.
- [x] 2. ~Use `@Evented()` as class decorator for all things that use `extends EventTarget`~ - the `js-async-init` 1.9.x is now integrated with `js-events`
- [x] 3. ~Use `addEventListener(callback)` instead of hardcoding all the relevant event names~ - Can use `EventDefault.name` instead.
- [x] 4. Encapsulated evented objects should have all their events captured and handled, the ones it cannot handle needs to be re-emitted
- [x] 5. The `events.ts` isn't properly setting up the event class hierarchy, they should be extending the abstract classes for the grouped events.
- [x] 6. Update to node v20 (including pkgs.nix, shell.nix, scripts for win and mac)
- [x] 7. Make sure that startup and shutdown of QUIC connections have no race conditions.
- [x] 8. Create 3 new issues from this:
         - Native multithreading for performance - need to bench this against socket buffer size increase
         - Connection Migration - should support it for the client, but not sure for serer
         - Server name check should support IP checks if the server name is just the IP - requires upstream fix - https://github.com/MatrixAI/js-quic/pull/53#issuecomment-1731099511
- [x] 9. Test build with `0.18.0` (we are currently 2 versions behind)
         - Note this requires an update to `boring` to v3. There are some notes on v3 fixing the windows build problem. https://github.com/cloudflare/boring/issues/121#issuecomment-1731403035 (So it's possible that `0.18.0` will be the build where windows succeeds!!)
- [x] 10. Renamed `toCanonicalIp` to `toCanonicalIP`
- [x] 11. Aligned `generateCertificate` with PK's `x509` module where we actually setup the proper subject and issuer common names along with SAN for testing `localhost` DNS and `127.0.0.1` and `::1` IP.
- [x] 12. Event flows from "error" to "close" to "stop", where recoverable errors results in an error event. But unrecoverable errors also go to "error" event that is then thrown upwards to result in `EventError` which by default results in an uncaught exception that represents a fail fast software error.
          - image
- [x] 13. TLS errors are now properly explained using the `CryptoError` enum. Note that this is unique to QUIC, where TLS 1.3 alert codes is offset by `0x0100`. Node's https doesn't really expose the alert codes, it just abstracts over it.

Prototyping `test.ts` for random tests.

<details>

```ts
import Logger, { LogLevel, StreamHandler, formatting } from '@matrixai/logger';
import { CryptoError } from './src/native';
import QUICClient from './src/QUICClient';
import QUICServer from './src/QUICServer';
import * as events from './src/events';
import * as utils from './src/utils';
import * as testsUtils from './tests/utils';

// process.on('uncaughtExceptionMonitor', (err, origin) => {
//   console.log('Caught exception:', err);
//   console.log('Exception origin:', origin);
// });

// process.on('unhandledRejection', (reason, promise) => {
//   console.log('Unhandled Rejection at:', promise, 'reason:', reason);
// });

// IT"S AN UNCAUGHT EXCEPTION
process.on('uncaughtException', (err, origin) => {
  console.log('Caught exception:', err);
  console.log('Exception origin:', origin);
});

async function main() {
  const logger = new Logger(`stream_1KiB Bench`, LogLevel.INFO, [
    new StreamHandler(
      formatting.format`${formatting.level}:${formatting.keys}:${formatting.msg}`,
      // formatting.format`${formatting.date}-${formatting.level}:${formatting.keys}:${formatting.msg}`,
    ),
  ]);
  const data1KiB = Buffer.alloc(1024);
  const tlsConfig = await testsUtils.generateTLSConfig('RSA');
  const quicServer = new QUICServer({
    config: {
      verifyPeer: false,
      key: tlsConfig.leafKeyPairPEM.privateKey,
      cert: tlsConfig.leafCertPEM,
      ca: tlsConfig.caCertPEM
    },
    crypto: {
      key: await testsUtils.generateKeyHMAC(),
      ops: {
        sign: testsUtils.signHMAC,
        verify: testsUtils.verifyHMAC,
      },
    },
    logger: logger.getChild('QUICServer'),
  });
  quicServer.addEventListener(
    events.EventQUICServerConnection.name,
    // @ts-ignore
    (evt: events.EventQUICServerConnection) => {
      const connection = evt.detail;
      connection.addEventListener(
        events.EventQUICConnectionStream.name,
        // @ts-ignore
        async (evt: events.EventQUICConnectionStream) => {
          const stream = evt.detail;
          process.stderr.write('>>>>>>>>> HANDLING THE QUIC SERVER STREAM\n');
          await stream.writable.abort();
          // try {
          //   await stream.writable.close();
          // } catch (e) {
          //   console.log('FROM CLOSING WRITABLE', e.name, e.message);
          // }
          // Consume until graceful close of readable
          try {
            for await (const _ of stream.readable) {
              // Do nothing, only consume
            }
          } catch (e) {
            console.log('FROM READING STREAM', e.name, e.message);
          }
          process.stderr.write('<<<<<<<< HANDLED THE QUIC SERVER STREAM\n');
        }
      );
    }
  );

  await quicServer.start();

  let quicClient: QUICClient;
  try {
    const host = utils.resolvesZeroIP(quicServer.host);
    quicClient = await QUICClient.createQUICClient({
      host: host,
      port: quicServer.port,
      config: {
        verifyPeer: true,
        ca: tlsConfig.caCertPEM
      },
      crypto: {
        ops: {
          randomBytes: testsUtils.randomBytes,
        },
      },
      logger: logger.getChild('QUICClient'),
    });
  } catch (e) {
    console.log('FAILED TO CREATE QUIC CLIENT', e.name);
    throw e;
  }

  const stream = quicClient.connection.newStream();
  const reader = stream.readable.getReader();
  const writer = stream.writable.getWriter();

  // Remember to test out of order here
  await reader.cancel();

  // Write some bytes!
  for (let i = 0; i < 100; i++) {
    await writer.write(data1KiB);
  }
  await writer.close();

  await testsUtils.sleep(100);

  // This is forcing the connection stop to occur, which is code 0
  // It waits however for the stream to gracefully close, which occurred
  // You still get the connection error early though without delays
  // If there is a delay, that will ensure that close is in fact sent out
  // Processed... and therefore, destroy here works fine too
  await quicClient.destroy({ force: false });

  await quicServer.stop({ force: false });

  // This would mean... that we don't force it... we wait gracefully for the streams to just close
  // And it should still work
  // So graceful closing works
  // await quicClient.destroy({ force: false });

  // What about non-graceful close?
  // What if I force destruction of the QUIC client?
  // Then what?
  // In this case, it won't wait for the streams to be closed gracefully
  // It cancels and aborts the streams
  // And then proceeds to immediately send connection close frame but allows the server to clean up

  // await quicClient.destroy({ force: true, applicationError: false, errorCode: 1 });

  // Ok this works too, and it's because the stream was in fact already closed earlier

  // Now what if we don't wait for the client to destroy?
  // await testsUtils.sleep(1000);
  // In that case client is destroying force
  // Sending out and timing out
  // And the server is process and graceful close
  // It should still work too

  // If the connections are all gone, we shouldn't need to do this
  // await quicServer.stop({ force: false });

  // What if we now try to force it here too?
  // await quicServer.stop({ force: true });
  // It works

  // let's see what happens if we shutdown both at the same time
  // await Promise.all([
  //   quicClient.destroy({ force: true, applicationError: false, errorCode: 1 }),
  //   quicServer.stop({ force: true }),
  // ]);
  // It works

  // What about gracefully stopping both concurrently?
  // await Promise.all([
  //   quicClient.destroy({ force: false }),
  //   quicServer.stop({ force: false }),
  // ]);
  // It works

  // Let's try not closing the streams properly
  // await Promise.all([
  //   quicClient.destroy({ force: true }),
  //   quicServer.stop({ force: true }),
  // ]);
  // That works too, so that will force close stuff

  // What about if graceful close, without closing any of the streams
  // await Promise.all([
  //   quicClient.destroy({ force: false }),
  //   quicServer.stop({ force: false }),
  // ]);

  //oh boy it is stuck!!
  // It is precisely stuck on quic client destruction
  // because the quic client stream exists
  // but the server does not... funnily enough
  // so the server's connection is immediately started and stopped
  // but the quic stream is still not fully resolved
  // which makes sense here

}

void main();
```

</details>

### Final checklist

* [ ] Domain specific tests
* [ ] Full tests
* [ ] Updated inline-comment documentation
* [ ] Lint fixed
* [ ] Squash and rebased
* [ ] Sanity check the final build

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
If the `QUICSocket` is encapsulated in the `QUICServer`. Then stopping the `QUICServer` should stop the `QUICSocket`. And this will result in an emission of `EventQUICSocketStop`.

If `QUICSocket` is injected into `QUICServer`. Then stopping the `QUICServer` should _not_ stop the `QUICSocket`. And this will _not_ result in an emission of `EventQUICSocketStop`.

When `EventQUICSocketStop` is emitted. It has to be listened by `QUICServer` whether it is encapsulated or injected. This event could emit at any time due to any problem or user-initiated call. Therefore we must proceed to then stop the `QUICServer`.

One issue is that when stopping the `QUICServer`, we are also stopping the `QUICSocket`. Which results in an emission of `EventQUICSocketStop`. If we handle this to stop the `QUICServer`, don't we have an infinite loop?

Well atm, it's a no, because due to `StartStop` and associated decorators, we are using locks to block and furthermore conditions to coalesce these calls. So the infinite loop is terminated by the async-init decorators.

However as a general pattern, we shouldn't depend on the async-init in this situation. There could be other situations where an event is emitted from another object that we need to handle, which causes to execute a pull-method which triggers another event of the same type, thus creating an infinite loop.

Therefore, rather than simply relying on async-init to cancel the infiniteness (not only is this relying on implicit behaviour, but it's not even guaranteed in the future). We need something else as a general pattern to prevent such things.

Here are some possibilities.

1. We stop listening for the `EventQUICSocketStop` when we perform the `quicSocket.stop()`. - This is rather error prone, as we it requires us to keep track of this context every time we call `quicSocket.stop()`. And I err against the side of things that require too much context to keep track of.
2. Could the handler itself terminate with a base case? How would it decide? It cannot decide based on whether `QUICSocket` is injected or encapsulated, because in either case the `EventQUICSocketStop` could be emitted. Perhaps instead it can rely on a certain state-variable representing the execution of `QUICServer.stop`?
3. Other solutions?

Note that solution 2 means rather than just calling `void this.stop()`, it would rely on checking if the status of the system is stopping. Like `if (this[stopping]) { ... }`.

Is this actually any better than solution 1? Or just relying on `void this.stop` since the decorator manages it.

I think it is better than solution 1 as it centralises logic.

It's better than simply relying on `this.stop` from the decorator because it is explicit and gives a model for future operations.

The presence of infinite loops here is primarily due to this 1 reason: the inability to easily distinguish if an event happens due to something I'm already doing. The only good solution is to rely on status conditionals representing the state of doing that operation.

**Comment by tegefaulkes** [comment]
I think it ties into the idempotent nature of the stop method. In this case it's handled by the decorator. but as a general rule, for things like this, it can only really stopped or destroyed once. So the stop or destroy event can only be emitted once. 

In the case of stop, it's emitted only once per state change since it could be started again. In that case it still prevents the cycle.

This might generalise as, any event that is the result of a state change, can only emit once per state change? we can refer to them as state events or... Once-lers? In any case, how does that sound for a general rule?

**Comment by CMCDragonkai** [comment]
Now on the topic of encapsulated events. Where `QUICServer` encapsulates `QUICSocket`. Another design decision is about how encapsulated events should be emitted out of `QUICServer`.

Firstly there will be "relevant" and "irrelevant" events to `QUICServer`.

The "relevant" events are events that `QUICServer` must react to.

The "irrelevant" events are events that `QUICSocket` does not need to react to.

In both cases, there's a question about whether such events should be bubbled upwards outside of `QUICServer`.

1. Does an event matter to the outside world? Is `QUICSocket` an entirely encapsulated system?
2. If we do bubble it up, how do we do this? Currently `Event` is not allowed to be re-dispatched. We can only either dispatch a new event that wraps the original event by setting the original event as the `detail` property of the new event, or we redispatch the original event by instantiating a new class of that same event, and copy any `detail` to this new instance.

In terms of 1. even if we could argue that certain events shouldn't be relevant. Dispatching such an event is still useful for "observability". Where it can be useful to debug the internal state of the system, such as for tracing. The question is whether such tracing should make use of these events, or if a separate system should be used for such a thing. It also important to note that events could represent "pre-" or "post-" op events. However we defaulted to `post-` op events to match the convention of Node's event emitters and most other JavaScript evented systems.

In terms of 2., dispatching an event chain can help maintain a trace of these concurrent operations, similar to maintaining a trace of exceptions that was thrown, caught and rethrown. Exceptions are a bit easier since you can rethrow the same exception. I think that there are 2 equivalences:

* Rethrowing an exception is equivalent to re-dispatching the same event class with the same details. (Since you cannot redispatch the exact same instance).
* Throwing up a new exception chaining the old exception is equivalent to dispatching a new event wrapping around the old event.

Based on this https://gist.github.com/CMCDragonkai/08266b1463158f4156f66d4bf077add6 for exceptions, I think the same guidelines apply here.

```
# EXCEPTION RERAISE/RETHROW
# this reraises the same exception, in this case
# it just means you couldn't handle the exception
try:
    raise Exception
except Exception as e:
    raise e
    # raise # this is equivalent and you won't need to bind the exception
    
# EXCEPTION HANDLING EXCEPTION
# this raises another exception in the handling of the first exception
# python will recognise this and report it as so
# only do this if you really have an exception while handling an exception
try:
    raise Exception
except Exception as e:
    raise Exception

# EXCEPTION CHAIN
# this raises a new exception and chains the new exception with the old exception
# use this when your code represents an onion of different layers each capable of handling different exceptions
try:
    raise Exception
except Exception as e:
    raise Exception from e
```

I think both would be applicable depending on the situation.

In the case of `QUICSocket` and `QUICServer`, I think due to informational tracing, it would make more sense to just re-dispatch with the same class. This would be most of the events that we would want to redispatch. Then only in certain cases would we want to chain it for some reason.

**Comment by CMCDragonkai** [comment]
> I think it ties into the idempotent nature of the stop method. In this case it's handled by the decorator. but as a general rule, for things like this, it can only really stopped or destroyed once. So the stop or destroy event can only be emitted once.
> 
> In the case of stop, it's emitted only once per state change since it could be started again. In that case it still prevents the cycle.
> 
> This might generalise as, any event that is the result of a state change, can only emit once per state change? we can refer to them as state events or... Once-lers? In any case, how does that sound for a general rule?

I think using `once: true` would actually in fact make sense here if the event handler could be specialised to that specific event that could trigger an infinite loop.

In situations where you have a common event handler, then `once` won't work because there could be other events you want to listen and handle all the time repeatedly.

**Comment by CMCDragonkai** [comment]
So it's possible to do this simultaneously:

1. Listen for "relevant" events, and handle it appropriately, as well as use `once` for things to terminate any infinite loops.
2. Listen for all events, and then the expectation is that all the events are "irrelevant", and thus can just be re-dispatched with the same class. The same-class redispatch can be done... but one then has to guarantee the signature of instantiating events. To do this, we can provide a `clone` method as part of a top-level root `Event` class. Similar to `js-errors` we can do `AbstractEvent` and provide a `clone` method.

**Comment by tegefaulkes** [comment]
I'm using this as scaffolding for the event with clone method for now. It will be replaced with your implementation.

```ts
type OptDetail<T> = T extends undefined ? {} : { detail: T };

class TempBaseEvent<T = undefined> extends Event {
  public readonly detail: T
  constructor(type: string, protected options?: EventInit & OptDetail<T>) {
    super(type, options);
    // @ts-ignore: Detail should be undefined here if it doesn't exist
    this.detail = options?.detail;
  }

  public clone(): this {
    // @ts-ignore: cheeky self prototype reference
    return new this.constructor(this.options);
  };
}
```

**Comment by CMCDragonkai** [comment]
As per https://github.com/MatrixAI/js-events/pull/2, it should be easy to find and replace all uses to just `AbstractEvent` too. And due to the automation inside, most of the time you can just do:

```
class EventX extends AbstractEvent<SomeType> {}
```

And that's enough to create the relevant event.

**Comment by CMCDragonkai** [comment]
Some notes on redispatch:

### Injection

Don't redispatch relevant and irrelevant events. Only handle relevant events.

### Encapsulation

Redispatch all events including relevant and irrelevant events

### On Redispatch

1. redispatch same event - only do this for "irrelevant" events
   - an info event on quic socket, is not an info event of quic server
2. redispatch chain event - only do this for "relevant" events
   - an error in quic socket, is an error of the quic server

Do 2. whenever there's an "equivalent" event on the domain model.

Do 1. when there is not.

When doing 2, the chain event structure should be always have a base type.

Consider this:

```
class EventQUICServerError extends EventQUICServer<Error | EventQUICSocketError> {}
```

Notice that I'm wrapping `Error | ErrorQUICSocketError` under `EventQUICServerError`.

* `QUICServer` might be encapsulating `QUICSocket`.
* If `QUICServer` encapsulates `QUICSocket`, any error event of `QUICSocket` is a relevant event to `QUICServer`. It gets handled, and the handling means `QUICServer` must destroy itself.
* This is a potential infinite loop, so we use `once` to terminate the loop.
* `QUICServer` redispatches `QUICSocket` using `QUICServerError` wrapping `QUICSocketError` because it's a relevant event and because a quic socket error is a quic server error.

This is not true for `QUICConnectionError`. While it is relevant to `QUICServer` for connection management, a quic connection error is not a quic server error. The quic server does not crash if there's a quic connection error. Thus redispatching upwards is purely informational. In this case, there is no need to wrap the event, and thus we redispatch the clone of it.

@tegefaulkes

**Comment by CMCDragonkai** [comment]
Let's see how the above structure plays out in code before reviewing.

**Comment by CMCDragonkai** [comment]
So one thing I've had to do is to introduce `EventAll` and `EventDefault`.

Furthermore my attempt at specialising the `name` property of `AbstractError`, `EventAll` and `EventDefault` fails to work because `tsc` won't accept the code even though it is now legal with native classes.

```
class Abc {
  // @ts-ignore
  public static name = `${this.name}`;
}
```

The above does not compile unfortunately. Even though it would be nice since we can continue using the same pattern like `addEventListener(EventAll.name, f)`.

I used one before called `EventAll.type`, but then it would be different from the regular `name` property that would be used if people defined their own events.

```
addEventListener(EventCustom.name, f);
addEventListener(EventDefault.type, f);
```

**Comment by CMCDragonkai** [comment]
Ok the change of nameclashes is quite low. So I'm just going to use `EventAll.name` and `EventDefault.name`.

**Comment by CMCDragonkai** [comment]
The `js-events` https://github.com/MatrixAI/js-events/pull/5 has made this comment possible:

https://github.com/MatrixAI/js-quic/pull/53#issuecomment-1700334819

2 examples of this is actually in the `js-events` tests.

Can follow that as a guideline on what to do @amydevs @tegefaulkes.

**Comment by CMCDragonkai** [comment]
> Some notes on redispatch:
> 
> ### Injection
> Don't redispatch relevant and irrelevant events. Only handle relevant events.
> 
> ### Encapsulation
> Redispatch all events including relevant and irrelevant events
> 
> ### On Redispatch
> 1. redispatch same event - only do this for "irrelevant" events
>    
>    * an info event on quic socket, is not an info event of quic server
> 2. redispatch chain event - only do this for "relevant" events
>    
>    * an error in quic socket, is an error of the quic server
> 
> Do 2. whenever there's an "equivalent" event on the domain model.
> 
> Do 1. when there is not.
> 
> When doing 2, the chain event structure should be always have a base type.
> 
> Consider this:
> 
> ```
> class EventQUICServerError extends EventQUICServer<Error | EventQUICSocketError> {}
> ```
> 
> Notice that I'm wrapping `Error | ErrorQUICSocketError` under `EventQUICServerError`.
> 
> * `QUICServer` might be encapsulating `QUICSocket`.
> * If `QUICServer` encapsulates `QUICSocket`, any error event of `QUICSocket` is a relevant event to `QUICServer`. It gets handled, and the handling means `QUICServer` must destroy itself.
> * This is a potential infinite loop, so we use `once` to terminate the loop.
> * `QUICServer` redispatches `QUICSocket` using `QUICServerError` wrapping `QUICSocketError` because it's a relevant event and because a quic socket error is a quic server error.
> 
> This is not true for `QUICConnectionError`. While it is relevant to `QUICServer` for connection management, a quic connection error is not a quic server error. The quic server does not crash if there's a quic connection error. Thus redispatching upwards is purely informational. In this case, there is no need to wrap the event, and thus we redispatch the clone of it.
> 
> @tegefaulkes

So this has changed a bit. On injection, we may redispatch the relevant event, if the handling of the relevant event, is itself an event on the object receiving the event.

**Comment by CMCDragonkai** [comment]
Rules for using js-events revised.

1. Dispatch event only after all state transition relevant to the event is done. This means events represent post-transition. This means subscribers always react to a post-transition state.
2. When an error event occurs in any given object `X` and is received by an outer object `Y`. Then it is `Y` responsibility to manage the lifecycle of `X`. But only if `X` is encapsulated within `Y`. Afterwards, `Y` will redispatch the `X` error event (whether encapsulated or not).
  image
3. When handling events, if it is possible to hit an exception on the handler (both synchronous and asynchronous), it must be caught and redispatched as an error. Here's an example (notice the usage of `AggregateError` here, but when using `js-errors`, set the `cause` to be the `AggregateError`). Example:
   ```
      protected handleEventXError = async (evt: EventXError) => {
        try {
          // Transition Y to errored state...
          if (this.isXEncapsulated) {
            // Only if it is encapsulated.
            await this.x.stop();
          }
          this.dispatchEvent(
            new EventYError({
              detail: evt,
            }),
          );
        } catch (err) {
          // Unexpected error is also dispatched
          this.dispatchEvent(
            new EventYError({
              // Aggregate error because it's actually 2 errors
              // If you use `js-errors`, then try making the cause an array
              // The array order should be
              detail: new AggregateError([err, evt.detail]),
            }),
          );
        }
      };
   ```
4. Say `X` emits error, then `Y` handles and tries to stop `X` then redispatches, then `Z` handles and tries to stop `Y`... etc all the way up to the root of the program `P`. It is important that at `P`, event handlers are added, otherwise errors will disappear to the ether.
5. Say `X` emits error, then `Y` handles and tries to stop `X`, but it fails at this point with a thrown exception. Then `Y` dispatches a new aggregate error. `Z` will handle this and try to stop `Y`. It may fail to stop `Y` too, in which case the same process repeats upwards.
6. Objects never listen on their own events.
7. Upon reacting to an event, mutations should occur before any event emission.
8. Event dispatch is always synchronous.
9. Event handlers which may cause errors should wrap the entire thing in a try catch that dispatches their domain error as it would be considered unexpected. That would be equivalent to calling await this.stop() so one can catch the exception.
10. The default handler should be used to redispatch the same instance of all encapsulated events.

In pull, handlers don't know who called them. In push, handlers always know who called them.

The usage of the event behaviour is tricky and not type-safe. Migrating to observables later in the future would enable these patterns in a more type-safe manner and allow us to automate this with higher order functions. But for libraries we have to stick with `EventTarget`.

**Comment by CMCDragonkai** [comment]
@tegefaulkes brought up a situation like this:

If an object has a pull-method that could result in an error, and the object itself is evented, does that mean:

1. Throw up the exception, but don't dispatch.
2. Dispatch an event error, but don't throw up the exception.
3. Dispatch an event error AND throw up the exception.

I think all 3 are possibly valid depending on the situation.

For 1., this makes sense if the pull-method doesn't actually do any state changes on the object. Thus the exception is only relevant to the caller.

For 2., this makes sense if you can say that the method is entirely internal to the library or module context. Like for example `QUICConnection.recv`.

For 3., this makes sense if the method performs a state change, and it's not an "internal" method. It is expected that things outside your library may call it. In this case, you have to document that it will dispatch and throw an exception. In which case, the user of the object has to decide what to do, whether it ignores one and handles the other.

**Comment by CMCDragonkai** [comment]
So for `QUICConnection.stop` it would need to do both dispatch and throw it upwards.

Note that in `QUICConnection.recv` which needs to do `void this.stop().catch(() => {})` is because `stop` may throw up an error, and it needs to ignore it, because the expectation is that the error would have been already dispatched by `QUICConnection.stop`.

**Comment by tegefaulkes** [comment]
As it's currently implemented, the `this.stop()` is triggered in 4 conditions. 
1. In `recv()` in response to a draining or closed state.
2. In `send()` in response to an error sending data through the socket.
3. In `send()` if the state transitioned to closed after sending data.
4. In the timer system in response to the connection timing out.

In cases 1, 3 and 4 it makes sense since we're responding to the the underlying quiche connection's state change.

2 is technically an internal error separate from quiche but it's a transport failure. This is the only one I can see emitting an error event that would trigger stop externally. I really don't like this since it's clean up logic critical to the function of `QUICConnection` that would need to handled external to the `QUICConnection` code and Maintained in 2 separate places in `QUICServer` and `QUICClient`. It makes things less maintainable.

Also, most errors coming out of quiche are obtained with `connection.localError()` or `connection.peerError()` after the connection has drained and closed.

**Comment by CMCDragonkai** [comment]
@tegefaulkes you will need to update the `pkgs.nix`, `shell.nix` to get node 20. Also there's a rule that you'll need to make use of `arguments` in `.eslintrc`. https://github.com/MatrixAI/js-events/blob/91a71b7c7ac04b8a29978533971dd0824da71af0/.eslintrc#L42

**Comment by CMCDragonkai** [comment]
> As it's currently implemented, the `this.stop()` is triggered in 4 conditions.
> 
> 1. In `recv()` in response to a draining or closed state.
> 2. In `send()` in response to an error sending data through the socket.
> 3. In `send()` if the state transitioned to closed after sending data.
> 4. In the timer system in response to the connection timing out.
> 
> In cases 1, 3 and 4 it makes sense since we're responding to the the underlying quiche connection's state change.
> 
> 2 is technically an internal error separate from quiche but it's a transport failure. This is the only one I can see emitting an error event that would trigger stop externally. I really don't like this since it's clean up logic critical to the function of `QUICConnection` that would need to handled external to the `QUICConnection` code and Maintained in 2 separate places in `QUICServer` and `QUICClient`. It makes things less maintainable.
> 
> Also, most errors coming out of quiche are obtained with `connection.localError()` or `connection.peerError()` after the connection has drained and closed.

In your 2, you would follow 2.

image

**Comment by CMCDragonkai** [comment]
> Also, most errors coming out of quiche are obtained with connection.localError() or connection.peerError() after the connection has drained and closed.

In this case, these errors are not errors of the `stop` itself. They should just be dispatched.

**Comment by tegefaulkes** [comment]
So based on discussion, 

The QUICSocket.send will not throw, but if it fails it will dispatch an error event. This event should ultimately cause a `QUICConnection.stop()` call. If it is managed by the `QUICClient` or `QUICServer` then handling is set up there based on encapsulation. It the `QUICSocket` is shared then the handling needs to be setup by whatever manages it.

Switching to this new pattern also means the `QUICConnection` shouldn't trigger a `stop()` call internally unless it drained and closed without error. If the `quicheConnection` enters the draining or closed state then we need to check for an error. Dispatch said error, then whatever is managing the connection, `QUICServer` or `QUIClient`, MUST call `stop()` on that connection while passing the relevant information back into it.

The `QUICServer` needs to trigger `QUICConnection.stop()` if it handles an error. If the `QUICSocket` is encapsulated then any socket errors needs to be handled and trigger stopping of the socket. Then re-dispatched so  whatever manages the `QUICServer` can clean up the `QUICServer`. It the `QUICSocket` is not encapsulated then what ever manages both the `QUICSocket` and `QUICServer` needs to handle their errors and clean them up.

Likewise for the `QUICClient`.

**Comment by CMCDragonkai** [comment]
When separating the functionality between encapsulated dependencies and injected dependencies, we have to basically have a boolean that branches out the functionality.

However this results in alot of boilerplate. Requiring a separate `xIsInjected` boolean for every dependency that may be encapsulated or injected.

Only a few dependencies make use of this distinction during runtime. Most of the time, this is actually only used for testing & mocking.

Consider for example in the 3 situations of EFS, QUIC. In EFS, the `db` can be encapsulated or injected. In QUIC, the `QUICSocket` can be encapsulated or injected. Both cases are legitimate usecases. We should definitely have a boolean that indicates the distinction.

Consider the case of `PolykeyAgent`. Almost all of its dependencies should just be fully encapsulated. The only reason to enable the ability to pass in `DB`,... etc is allow mocking or unit testing. But the amount of boilerplate to support all of the dependencies would be HUGE!

The only way to make such a thing manageable would be to introduce parameter decorators on the constructor that automatically produces properties.

However I don't want to do that right now, it might introduce too much complexity. Instead let's do something different.

1. Where we have legitimate reasons for encapsulation/injection, we continue doing it with a manually specificed `xIsInjected` or equivalent boolean.
2. Where it's only there for testing, we can remove it..., and instead rely on module mocking in jest to make use of it. See: https://jestjs.io/docs/mock-functions#mocking-modules

This doesn't have to be a wholesale change immediately... we can just keep an issue in PK and slowly apply this across the ecosystem. In some cases, optional injection can still be kept since there's barely any lifecycle related activities, or the relevant objects in question are not evented objects.

**Comment by CMCDragonkai** [comment]
If dispatching `EventQUICServerError`, means that `QUICServer` is in an errored state, does that mean we need a proper state transition like `this.error()`.

Perhaps instead we would say `this.stop({ error })` as indicative of transitioning to a stopped-error state.

**Comment by CMCDragonkai** [comment]
So if error-ring is a terminal state, it might be easier to simply react on the stopped state, and check if that was due to an error not.

That would keep it quite simple if we could do this.

**Comment by CMCDragonkai** [comment]
3.0.1 of `js-events` brings in the ability to use `evt.target`. That `target` will always point to the evented object. So if I get a `EventQUICConnectionStop` event I can check `evt.target` to get the `QUICConnection` that hit that event.

**Comment by CMCDragonkai** [comment]
Ok so I got rid of the `EventDefault` for now since it was overcomplicating it. Informational observation can be left for later.

I'm attempting to follow the rules where pull methods always throw up exceptions and thus event handlers is where exceptions must be caught and converted to an error.

**Comment by CMCDragonkai** [comment]
Regarding the usage of the monitor inside `QUICConnection.start`. This was moved here from #48.

The reason was that nothing would have a reference to the `QUICConnection`. But that isn't entirely true.

We actually have the `QUICConnection` as part of the connection map. So it is possible that, there may be something in between the `recv` and `send` call.

But @tegefaulkes you didn't mention that you were keeping the monitor usage.

**Comment by CMCDragonkai** [comment]
Also this code doesn't quite make sense to me:

```
    await this.withMonitor(mon, this.lockbox, RWLockWriter, async (mon) => {
      if (!mon.isLocked(this.lockCode)) {
        return mon.withF(this.lockCode, async (mon) => {
          return this.send(mon);
        });
      }
    });
```

Why did you do `if (!mon.isLocked(this.lockCode)) { ... }`?

**Comment by CMCDragonkai** [comment]
I just realised you're not actually locking the monitor when you pass it in. You are simply sharing the monitor.

**Comment by CMCDragonkai** [comment]
This seems to make more sense:

```ts
      await Promise.race([
        Promise.all([
          withF(
            [contextsUtils.monitor(this.lockBox, RWLockWriter)],
            async ([mon]) => {
              await mon.lock(this.lockCode)();
              if (data != null) {
                await this.recv(
                  data,
                  { host: this._remoteHost, port: this._remotePort },
                  mon,
                );
              }
              await this.send(mon);
            }
          ),
          this.establishedP,
          this.secureEstablishedP,
        ]),
        abortP
      ]);
```

**Comment by CMCDragonkai** [comment]
Notice by using the resource acquisition pattern, you don't need to use `mon.withF` again. It's unnecessary. It's already provided by making use of the resource acquisition of the monitor.

In this case we are ensuring that within the call graph of both of those `recv` and `send` calls, that any other calls outside must wait until it completes.

**Comment by CMCDragonkai** [comment]
Some changes I'm doing:

1. All pull-methods always throw exceptions under errors.
2. Event handlers decide whether to dispatch events upon errors, depending on the type of the error, otherwise let's them bubble up as software errors that will shutdown the program by going to the unhandled promise rejection/unhandled exception.
3. The `QUICConnection.createQUICConnection` is removed entirely. This `QUICConnection` is a `StartStop` pattern. And thus should not have an async creator at all. Instead a constructor and `start` and `stop` can be used.
4. The `QUICServer` can then construct the connection first, then set it to the connection map of the socket, since the socket is "managed" by the server optionally. And then run the `start`.
5. This also means `QUICConnection.start` is what is being timed. So the `minIdleTimeout` is moved there.
6. If there's an error... we may need to stop the underlying connection. This means it's not possible to just call `QUICConnection.stop` since that can only be called if `QUICConnection.start` completed successfully, instead I'm stopping in the underlying connection properly there by forcing it. And since it wasn't setup properly, I believe I need to force this closure without waiting...
7. Where did stream force destroy go? Doesn't make sense why it got removed.

**Comment by CMCDragonkai** [comment]
When we force close a connection due to not completing a start, is it an application error or not?

The code in staging is set to `0` being an application error. Or it uses the `reasonToCode`. I don't think this makes sense.

**Comment by CMCDragonkai** [comment]
I think I'll remove the `QUICConnection.withMonitor`, it's entirely superfluous.

I also don't quite understand why it even bothers to say that if the locking code is not locked, it will then create a monitor locking it.

The whole point of the monitor is to be re-entrant. Meaning given the same monitor, locking the same key is a noop. So there shouldn't be any need to have a conditional checks.

**Comment by CMCDragonkai** [comment]
Ok there are some things I'm going to require from `js-errors` and `js-async-init`.

1. `js-errors` should supply a `checkError` function take takes `(e, (e) => bool)`. This can recursively check if an error exists within an "error graph" through the `cause` property as well as the aggregate error array.
2. `js-async-init` - because events need to be post-transition, this means `XStopped` or `XStarted` events should be part of the decorator class to ensure this to be the case.

**Comment by CMCDragonkai** [comment]
It doesn't make much sense to me that when `QUICConnection.stop` is called we have to do `this.setConnTimeoutTimer`.

**Comment by CMCDragonkai** [comment]
I've brought in `js-errors` and `js-events` to bring in the new `checkError` and also the ability for `@StartStop` and related decorators to automatically emit events.

**Comment by CMCDragonkai** [comment]
I'm looking over the custom TLS verification. And referring to https://github.com/MatrixAI/js-quic/pull/26.

The implementation doesn't make much sense to me. There's a lack of comments and clear indication as what all these steps are supposed to do. I think it needs to be revisited.

```
      // Checking if the packet was a short frame.
      // Short indicates that the peer has completed TLS verification
      if (!this.shortReceived) {
        const header = quiche.Header.fromSlice(data, quiche.MAX_CONN_ID_LEN);
        // If short frame
        if (header.ty === 5) {
          this.shortReceived = true;
        }
      }
      // Checks if `secureEstablishedP` should be resolved. The condition for
      //  this is if a short frame has been received and 1 extra frame has been
      //  received. This allows for the remote to close the connection.
      if (!this.secured && this.shortReceived && !this.conn.isDraining()) {
        if (this.count >= 1) {
          this.secured = true;
          this.resolveSecureEstablishedP();
        }
        this.count += 1;
      }
```

There's no explanation about what the purpose of count is for.

I don't understand this kind of code. @tegefaulkes can you explain all of this?

**Comment by CMCDragonkai** [comment]
Why is custom verification done on `send`, and not on `recv`? Seems like a strange place to do so.

Is it because connections are not fully established until `send` has occurred?

**Comment by CMCDragonkai** [comment]
I'm going to need explanations on:

1. How the custom TLS works and why it involves so many different checks, like `customVerified`, `shortReceived`, and `count`. Just seems like alot of this can be simplified to just one thing.
2. How the `establishedP` works and `secureEstablishedP` works.
3. The connection time out, how is this maintained.
4. The relationship of `start` and `stop` to `recv` and `send`.
5. Why `QUICStream` doesn't have a force destruction anymore.

One of the key things I'm changing is to ensure that that state changes are now being handled by the event handlers, rather than being done by the `start` and `stop` calls.

**Comment by CMCDragonkai** [comment]
> As it's currently implemented, the `this.stop()` is triggered in 4 conditions.
> 
> 1. In `recv()` in response to a draining or closed state.
> 2. In `send()` in response to an error sending data through the socket.
> 3. In `send()` if the state transitioned to closed after sending data.
> 4. In the timer system in response to the connection timing out.
> 
> In cases 1, 3 and 4 it makes sense since we're responding to the the underlying quiche connection's state change.
> 
> 2 is technically an internal error separate from quiche but it's a transport failure. This is the only one I can see emitting an error event that would trigger stop externally. I really don't like this since it's clean up logic critical to the function of `QUICConnection` that would need to handled external to the `QUICConnection` code and Maintained in 2 separate places in `QUICServer` and `QUICClient`. It makes things less maintainable.
> 
> Also, most errors coming out of quiche are obtained with `connection.localError()` or `connection.peerError()` after the connection has drained and closed.

Case 3 is actually a socket error, and should be handled in `QUICSocket` event handler.

In the other 3 situations, it can make sense for `QUICConnection.stop` to be called automatically in response to changes. However the error handling needs to be improved, I don't like how its exceptions and events is constructed and emitted.

Since `StartStop` now automatically emits `EventQUICConnectionStopped`... then a question is whether the closure of the connection due to local error/remote error or timeout should be separate events. Since it's not possible to add details to the `EventQUICConnectionStopped` anyway.

It sort of depends on what exactly will be capturing these events... suppose one is using a quic server. A connection is received.... and runs for a while, and then an error occurs on the connection and the connection is now stopped. How does one know about this error...? One could listen for connection error events I guess...

**Comment by tegefaulkes** [comment]
Addressing questions PT1.

1. Checking the conditions for when we consider the connection secured by TLS is very finicky to work out. I feel the comments do describe what is happening if not in a lot of detail. The count is to track the number of frames after the short frame has be received. As the comments mention the condition for secured is short +1 frame. The extra frame is to allow the remote to reject the connection via custom TLS logic. The count could be replaced with a simple state machine.

Checking if the connection is draining is to prevent the secured established condition if the connection was shutting down.

But yes, as discussed this whole thing can be simplified as a state machine.

2. established is resolved once the quiche connection has established. This is the first step of the connection establishment. Established just allows data to be sent but TLS has not completed yet. IF an error happens before established then we reject the promise. This just the main way we return the error when awaiting for establishment.

secure establishment is when the TLS has completed locally and remotely and we don't expect TLS to fail beyond this point. This is then we consider the connection fully established for our purposes. the condition for this is described above. If some problem happens before secure establishment completes the we reject it with the appropriate error. This is just how we return the error when awaiting for secure establishment.

3. We check the timeout and create a timer with the `setConnTimeOutTimer` method. This sets up the handler and the timer. If the timer exists then we reset the timer with a new delay. The handler it creates triggers stop if the connection had timed out. If not it triggers a send and creates a new timer with the new delay. The main way of this timer cleaning up is if `connection.timeout()` returns null. I decided that was the source of truth for that decision.

**Comment by tegefaulkes** [comment]
#### question 4. 

I'm not sure if I understand the question. Start and stop create and destroy the state respectively, recv and send just process incoming and outgoing data.

#### question 5.

From the perspective of the `QUICStream`, destruction is only ever forced. But after reviewing this it does seem weird. when destroying the streams we're awaiting the destroy method, but we don't actually await any state change inside the destroy method. looks like the connection is awaiting the streams to end with `stream.destroyedP`. I could move this logic into the stream destroy method.

So yes, this should function the same way as the other layers. `QUICStream.destroy()` should have a force option and await the destruction of the stream within it. A simple change assuming we don't run into any deadlocks with question 6.

#### question 6.

 We can do this, but we'll have to work around any deadlocking if it comes up. I know `QUICConnection` needs to process incoming packets during a draining state. I think no packets are sent while draining. So if we enter a draining state, we can't hold a lock on the monitor while awaiting stop.

#### question 7.

Is this a trick question? It's how we send data on a stream. I need more context here.

**Comment by CMCDragonkai** [comment]
I'm going to see what happens if I break 2 rules.

1. That objects can listen on their own events, such as listening for their own error event and proceed to `stop`.
2. That we can just `void this.stop({ force: true } );` especially if any errors that occur during stopping become software bugs.

**Comment by CMCDragonkai** [comment]
It seems to make sense that if `QUICConnection` was stopped locally with/without an error, that error is sent to the other side and thus is not an error of the `QUICConnection` itself.

If the remote side closed it gracefully, then again it's not an error.

If the remote side closed it with an error, then we can say that the `QUICConnection` suffered an error.

If the `QUICConnection` send failed on sending to the `QUICSocket`, then that's also an error on the `QUICConnection`.

File: src/QUICSocket.ts [hunk 1]
```diff
@@ -63,13 +88,13 @@ class QUICSocket extends EventTarget {
...
-        // This is not a critical error, but should be checked.
-        this.dispatchEvent(new events.QUICSocketErrorEvent({ detail: e }));
+      if (e.message === 'BufferTooShort' || e.message === 'InvalidPacket') {
+        return;
       }
-      return;
+      // If the error is niether `BufferTooShort` or `InvalidPacket`, this
+      // may indicate something went wrong in the header parsing, which should
+      // be a software error.
+      throw e;
```
Comment (tegefaulkes) [inline src/QUICSocket.ts:97]: We absolutely should not throw here. Any invalid packets should be discarded otherwise the program **WILL** crash due to random internet traffic.

Comment (CMCDragonkai) [reply src/QUICSocket.ts:97]: That's not what the comment said.

Comment (CMCDragonkai) [reply src/QUICSocket.ts:97]: If the comment is wrong it should have been fixed. In which case all errors could just be ignored and there's no need to check the error message at all.

Comment (tegefaulkes) [reply src/QUICSocket.ts:97]: I misread this, nevermind.

Comment (CMCDragonkai) [reply src/QUICSocket.ts:97]: It should be tested though, I've never tested it with random binary data.

Comment (tegefaulkes) [reply src/QUICSocket.ts:101]: From what I recall, there is at least 1 test that throws random data through the socket, let me find it.

Yeah at `tests/QUICClient.test.ts:659` under `describe('handles random packets'...`

**Comment by tegefaulkes** [comment]
I've updated the `QUICStream` to avoid using `void promise` wherever possible. Right now the `cancel()` still does this but it's required to be synchronious.

There may be deadlocks due to it waiting for calls to the `connection.send` but I can only tell by testing and we're not back to that stage yet.

I'll review the comments and see if I can expand them based on what you did in `QUICSocket`.

**Comment by CMCDragonkai** [comment]
The `QUICConnection` should behave in this way:

```
    // If the connection timed out, it's an error
    // If the connection operations failed (runtime IO errors), it's an error
    // If the remote side closed the connection with an error, it's an error
    // if the remote side closed the connection without error, it's not an error
    // If the local side closed the connection with an error, it's not an error
    // If the local side closed the connection witout error, it's not an error
```

**Comment by CMCDragonkai** [comment]
image

Because of this `connection.stop({ force: true });` doesn't really do anything except force destroy the streams (by not waiting for a graceful close of streams).

And therefore as quiche connection is entering a draining state, we just wait until the idle timeout is exhausted, and then `connection.stop` will return.

Again this simplifies `connection.stop({ force: true });` and we can say that any exceptions thrown here would be considered a software bug, not a runtime error.

**Comment by CMCDragonkai** [comment]
Within `connection.stop`, all of its error checks should be moved or removed. Remote error should be checked in `recv`. Local errors are not errors for `QUICConnection` so there's no need to do anything for that. Timeout errors can occur inside the idle timeout timer.

**Comment by CMCDragonkai** [comment]
So a few things.

1. We actually have to attach event listeners prior to start, and remove listeners after stop. This is because if we did the other way around we'd miss `Start`, `Started`, `Stop` and `Stopped` events.
2.  `QUICServer` actually does have to define the connection event handlers as properties because that's the only way we can remove the handlers when doing a regular `QUICServer.stop`.
3. There's actually a race condition when starting a quic connection. I believe this already existed in the existing code, it was just not obvious until now.

image

The above screenshot shows both `QUICSocket.handleSocketMessage` and `QUICServer.newConnection`.

You can see that when we do:

```ts
await connection.start({ data }, { timer: this.minIdleTimeout })`
```

The `data` option parameter is the same `data` used in:

```ts
      // No matter the connection state, we will send in the `recv` and `send` calls
      await connection.withMonitor(async (mon) => {
        await mon.lock(connection.lockingKey)();
        await connection.recv(data, remoteInfo_, mon);
        await connection.send(mon);
      });
```

So basically this means starting a connection involves reading that initial `data`.

However after starting the connection, we end up re-using that same initial data for the `recv` and `send` pairs.

Inside the `QUICConnection.start` we now also perform a `recv` and `send` pair.

Obviously we can see an issue here, we shouldn't be re-processing the same initial data twice.

**Comment by CMCDragonkai** [comment]
For problem 3. there's a few ways to solve this.

1. Move the `recv` and `send` pair in `QUICSocket.handleSocketMessage` to be used only when the connection already exists. That way, when accepting a new connection, we can just rely on the `QUICConnection.start` to perform the `recv` and `send` pair.
2. Don't do the `recv` and `send` pair inside `QUICConnection.start`... and do the `recv` and `send` pair inside the `QUICSocket.handleSocketMessage`. If this is the case, what is the point of `QUICConnection.start`... it's sort of useless.

So I think solution 1 is the correct one. It ensures  that starting a connection is self-contained, and it sort of makes sense, as awaiting `start` means the connection is fully started and ready to go instead of expecting outside `send` and `recv` pairs. From `QUICSocket.handleSocketMessage` perspective, if it is dealing with a new connection, it will let the `QUICServer` handle all of it (and respectively the `QUICConnection`). But if it's an existing connection, it can directly interact with it by doing the `recv` and `send` pair.

**Comment by CMCDragonkai** [comment]
So the way I actually solved it is to move the `recv` and `send` pair from `QUICConnection.start` to the bottom of `QUICServer.newConnection`.

That kept the starting and stopping of connections consistently managed by `QUICServer`, while `QUICSocket` only performed the `recv` and `send` pairs when the connection already existed.

Comments added to clarify the concurrent procedures for starting a `QUICConnection` as this is quite a tricky procedure.

**Comment by CMCDragonkai** [comment]
Now that `QUICConnection.start` simplified to just:

```
      await Promise.race([
        Promise.all([
          this.establishedP,
          this.secureEstablishedP,
        ]),
        abortP,
      ]);
```

Why do we even bother waiting for both `establishedP` and `secureEstablishedP`?

Why not just use `establishedP` to represent both the establishment and secure establishment?

We need to review the TLS mutual verification logic @tegefaulkes since I still think the counter is weird.

**Comment by CMCDragonkai** [comment]
Some extra questions about `QUICConnection`.

1. Why is max idle timer not started inside `QUICConnection.start`? Surely it should start ticking as soon as we call it.

**Comment by CMCDragonkai** [comment]
I believe `QUICServer` is now fully refactored too.

What's left is:

* `QUICConnection`
* `QUICClient`
* `QUICStream` - if everything is understood here?

@tegefaulkes review the `QUICServer` too, and also there's some comments inside `QUICConnection` that require addressing.

**Comment by CMCDragonkai** [comment]
We will need to start testing tomorrow.

**Comment by CMCDragonkai** [comment]
The TLS checking logic should be moved into the `recv` and work against these rules:

```
  // established means - I am established (it doesn't mean both sides are established)
  // As soon as I am established, I can check for the peer certificates
  // If the peer certificates is NULL
  // That means there was no certificates supplied
  // It should not be possible for an empty array (if it is, use `never()`)

  // verifyPeer: true, verifyCallback: true
  //   - if peer doesn't supply certs, it's a TlsFail (local error: 327)
  //   - if peer supplies bad certificates - no TLS fail, but verifyCallback will run
  //   - if peer supplies good certificates - no TLS fail, but verifyCallback will run

  // verifyPeer: true, verifyCallback: false
  //   - if peer doesn't supply certs, it's a TlsFail (local error: 327)
  //   - if peer supplies bad certificates - it's a TlsFail (local error: 304)
  //   - if peer supplies good certificates - no TLS fail

  // verifyPeer: false, verifyCallback: true
  //   - if peer doesn't supply certs, no TLS fail
  //   - if peer supplies bad certificates - no TLS fail, ignore verifyCallback
  //   - if peer supplies good certificates - no TLS fail, ignore verifyCallback

  // verifyPeer: false, verifyCallback: false
  //   - if peer doesn't supply certs - no TLS fail
  //   - if peer supplies bad certficates - no TLS fail
  //   - if peer supplies good certificates - no TLS fail

  // verifyAllowFail will become a derived option of verifyCallback
  // calculate the option change in `config.ts`

  // That means during the recv() call, you want to do this:
  //   - check if you get a TlsFail exception
  //     - check the local error
  //     - connection is automatically closed
  //     - dispatch error event
  //     - throw error
  //   - check if we are established
  //     - if we are verifyPeer && verifyCallback true
  //       - check if peer certificates is null - if so, pass
  //       - otherwise, call verifyCallback
  //       - if fail, 304, dispatch error event, throw error
  //    - else
  //       - pass
```

Note that 372 means no certs. 304 means bad certs.

**Comment by CMCDragonkai** [comment]
This also means we can just wait for `secureEstablishedP`, and remove `establishedP` in `QUICConnection.start`.

Also both peer error and local error are error events for `QUICConnection`. But if someone were to call `QUICConnection.stop()` with an error, it shouldn't be an error event. To achieve this you might need to not check for local error or peer error under `send`.

**Comment by CMCDragonkai** [comment]
QUICStream will never trigger `QUICConnection.recv` right? It will only trigger `QUICConnection.send`?

**Comment by CMCDragonkai** [comment]
@tegefaulkes you mentioned that in one particular case, there may be an issue with calling `close` in the middle of the handshake.

I've found that this is not a problem from the server side, but there appears to be a bug in quiche where it can result in a problem on the client side.

Specifically in the RSA scenario with custom verification callback a bad server certificate.

In the case where we don't use a custom verification callback, the expected behaviour is:

```
    RSA fail verifying server with bad server certificate (TlsFail 304)
      ✓ client connect (2 ms)
      ✓ client dialing (1 ms)
      ✓ client and server negotiation (4 ms)
      ✓ server accept (2 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client -initial-> server
      ✓ client <-handshake- server (36 ms)
      ✓ client has local error TlsFail 304
      ✓ client -handshake-> server (4 ms)
      ✓ server has peer error TlsFail 304
      ✓ client and server close (44 ms)
```

You can see that when the server sends the handshake to the client, the client experiences a local `TlsFail 304` error.

However if we attach a custom verification callback, this overrides the underlying verification function so that it always passes.

In that scenario, we are supposed to there perform our custom TLS verification.

We can imagine a call like `await verifyCallback(...)` to throw, and then translate this to a:

```ts
clientConn.close(false, 304, Buffer.from(''))
```

While this works for the client, and the client's connection after sending a short frame to the server enters draining state and eventually closes, the server receives the short frame, but it doesn't enter a draining state.

In fact, the server connection just becomes dead, but without any draining. The client connection effectively closes, and leaves the server connection to idle until it times out.

It's interesting that this does not happen when we don't use a custom verification callback.

This tells me that quiche is expecting to send a handshake frame, and in this particular case you cannot close the connection.... This is definitely an upstream bug for quiche, but it's an edge case.

To solve this will be tricky. Because it only occurs when the client receives a handshake frame that succeeds due to the custom verification override.

We would have to special case this situation, and then send a regular handshake frame back to the server, and only afterwards perform the `clientConn.close(false, 304, Buffer.from(''));`.

**Comment by CMCDragonkai** [comment]
In the above pseudocode for TLS: https://github.com/MatrixAI/js-quic/pull/53#issuecomment-1707642882

We are just checking the custom callback as soon as we have done `recv` and where the connection is established, which it is in this case.

In normal cases this would work (normal meaning the server can do this with a custom verification callback).

But due to the above problem with RSA handshake, we cannot immediately close. We have to call `send` first, before calling `close`.

One way to solve this is by doing the same thing symmetrically on both sides.

That means in these cases, whenever we have a custom verification callback, after the recv call, we can do check the custom verification callback, but rather than immediately calling `close` there, we instead change it so that we always end up calling `send` before sending `close`.

This means the order of events should be in case of custom tls callback:

```
recv
  - custom verify callback failure
send
close IF custom verify callback failed
  - send
```

However this only needs to be done in the context of custom verify callback. If the custom verify callback isn't involved, we could instead do:

```
recv
  - close on TLS fail
send
```

**Comment by CMCDragonkai** [comment]
In a way the above hack is probably required simply because we are doing custom verification at the JS level, and not at the Rust level. The original plan was for the custom verification function to just be called from Rust to JS. But you hit some problem achieving that. Maybe some problem with the napi bridge, and runtime incompatibility with Rust's boringssl and how JS functions work (which could be asynchronous).

By not doing this, we are circumventing the normal way of doing TLS verification in quiche. And so... now we introduce this other hack here.

**Comment by tegefaulkes** [comment]
Based on discussion. The general flow is recv -> process streams -> send -> process state [-> further sends]

This mainly means the following changes.
1. Remove any state checking from recv
2. processing streams is done inside of send as the first step.
3. A failure in sending due to the socket is emitted as an error event that triggers QUICConnection.stop()
4. processing state for a connection is all moved to `processState()` which is called at the end of send. This includes the custom TLS verification logic.
5. If a state change triggers stopping then this is emitted as an event which then calls `QUICConnection.stop()`.

**Comment by CMCDragonkai** [comment]
I think custom TLS verification should occur before step 2.

That should accurately match what happens when it's a normal TLS failure.

**Comment by CMCDragonkai** [comment]
I've now done the proper split for both RSA and ECDSA tests, it shows that the intermediate close in the middle of the handshake is indeed affecting both RSA and ECDSA, and probably will affect Ed25519 the same.

**Comment by CMCDragonkai** [comment]
What's the `streamStats` function for?

**Comment by tegefaulkes** [comment]
In quiche? it returns bunch of statistics for that connection. Might be useful to have on `QUICConnection`.

**Comment by CMCDragonkai** [comment]
All native TLS tests passing.

<details>

```
[nix-shell:~/Projects/js-quic]$ npm test -- ./tests/native/tls

> @matrixai/quic@0.0.21 test
> jest ./tests/native/tls

Determining test suites to run...
GLOBAL SETUP
 PASS  tests/native/tls/rsa.test.ts
  native/tls/rsa
    RSA success with both client and server certificates
      ✓ client connect (4 ms)
      ✓ client dialing (1 ms)
      ✓ client and server negotiation (4 ms)
      ✓ server accept (2 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client -initial-> server
      ✓ client <-handshake- server (2 ms)
      ✓ client is established (1 ms)
      ✓ client -handshake-> server (1 ms)
      ✓ server is established
      ✓ client <-short- server (1 ms)
      ✓ client -short-> server
      ✓ client and server established (2 ms)
      ✓ client close (61 ms)
    RSA success with only server certificates
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (2 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client -initial-> server
      ✓ client <-handshake- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -handshake-> server
      ✓ server is established (1 ms)
      ✓ client <-short- server (1 ms)
      ✓ client -short-> server
      ✓ client and server established (2 ms)
      ✓ client close (44 ms)
    RSA fail verifying client with bad client certificate (TlsFail 304)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (2 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client -initial-> server
      ✓ client <-handshake- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -handshake-> server (27 ms)
      ✓ server has local error TlsFail 304
      ✓ client <-handshake- server (2 ms)
      ✓ client has peer error TlsFail 304 (1 ms)
      ✓ client and server close (29 ms)
    RSA fail verifying client with no client certificate (TlsFail 372)
      ✓ client connect (1 ms)
      ✓ client dialing
      ✓ client and server negotiation (1 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server
      ✓ client -initial-> server
      ✓ client <-handshake- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -handshake-> server (1 ms)
      ✓ server has local error TlsFail 372 (1 ms)
      ✓ client <-handshake- server (3 ms)
      ✓ client has peer error TlsFail 372 (1 ms)
      ✓ client and server close (26 ms)
    RSA fail verifying server with bad server certificate (TlsFail 304)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (2 ms)
      ✓ client <-initial- server
      ✓ client -initial-> server
      ✓ client <-handshake- server (2 ms)
      ✓ client has local error TlsFail 304
      ✓ client -handshake-> server (2 ms)
      ✓ server has peer error TlsFail 304
      ✓ client and server close (24 ms)
    RSA fail with no server certificates (InternalError 1)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (1 ms)
      ✓ server accept (2 ms)
      ✓ server has local error 1 (1 ms)
      ✓ client <-initial- server (4 ms)
      ✓ client has peer error 1
      ✓ client and server close (2998 ms)
    RSA with custom verify callback
      RSA success with both client and server certificates
        ✓ client connect
        ✓ client dialing (1 ms)
        ✓ client and server negotiation (1 ms)
        ✓ server accept (2 ms)
        ✓ client <-initial- server
        ✓ client -initial-> server (1 ms)
        ✓ client <-handshake- server (1 ms)
        ✓ client is established (1 ms)
        ✓ client -handshake-> server (1 ms)
        ✓ server is established (1 ms)
        ✓ client <-short- server
        ✓ client -short-> server
        ✓ client and server established (2 ms)
        ✓ client close (36 ms)
      RSA success with only server certificates
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (2 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client -initial-> server
        ✓ client <-handshake- server
        ✓ client is established (1 ms)
        ✓ client -handshake-> server (1 ms)
        ✓ server is established
        ✓ client <-short- server
        ✓ client -short-> server (1 ms)
        ✓ client and server established (1 ms)
        ✓ client close (31 ms)
      RSA fail verifying client with bad client certificate (TlsFail 304)
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (2 ms)
        ✓ client <-initial- server
        ✓ client -initial-> server (1 ms)
        ✓ client <-handshake- server (1 ms)
        ✓ client is established (1 ms)
        ✓ client -handshake-> server (32 ms)
        ✓ server has local error TlsFail 304 (1 ms)
        ✓ client <-short- server (2 ms)
        ✓ client has peer error TlsFail 304
        ✓ client and server close (25 ms)
      RSA fail verifying client with no client certificate (TlsFail 372)
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (2 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client -initial-> server
        ✓ client <-handshake- server (1 ms)
        ✓ client is established
        ✓ client -handshake-> server (3 ms)
        ✓ server has local error TlsFail 372
        ✓ client <-handshake- server (2 ms)
        ✓ client has peer error TlsFail 372
        ✓ client and server close (26 ms)
      RSA fail verifying server with bad server certificate (TlsFail 304)
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (2 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client -initial-> server
        ✓ client <-handshake- server (3 ms)
        ✓ client -handshake-> server (1 ms)
        ✓ client has local error TlsFail 304
        ✓ client -short-> server (2 ms)
        ✓ server has peer error TlsFail 304
        ✓ client and server close (25 ms)

 PASS  tests/native/tls/ed25519.test.ts (6.92 s)
  native/tls/ed25519
    Ed25519 success with both client and server certificates
      ✓ client connect (4 ms)
      ✓ client dialing (1 ms)
      ✓ client and server negotiation (4 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -initial-> server (1 ms)
      ✓ server is established
      ✓ client <-short- server
      ✓ client -short-> server (1 ms)
      ✓ client and server established (2 ms)
      ✓ client close (56 ms)
    Ed25519 success with only server certificates
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept
      ✓ client <-initial- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -initial-> server
      ✓ server is established
      ✓ client <-short- server (1 ms)
      ✓ client -short-> server
      ✓ client and server established (1 ms)
      ✓ client close (24 ms)
    Ed25519 fail verifying client with bad client certificate (TlsFail 304)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client is established
      ✓ client -initial-> server (36 ms)
      ✓ server has local error TlsFail 304 (1 ms)
      ✓ client <-handshake- server (1 ms)
      ✓ client has peer error TlsFail 304
      ✓ client and server close (19 ms)
    Ed25519 fail verifying client with no client certificate (TlsFail 372)
      ✓ client connect (1 ms)
      ✓ client dialing
      ✓ client and server negotiation (1 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client is established
      ✓ client -initial-> server (2 ms)
      ✓ server has local error TlsFail 372 (1 ms)
      ✓ client <-handshake- server (2 ms)
      ✓ client has peer error TlsFail 372
      ✓ client and server close (14 ms)
    Ed25519 fail verifying server bad server certificate (TlsFail 304)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client has local error TlsFail 304 (1 ms)
      ✓ client -initial-> server (2 ms)
      ✓ server has peer error TlsFail 304
      ✓ client and server close (2999 ms)
    Ed25519 fail with no server certificates (InternalError 1)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (2 ms)
      ✓ server has local error 1
      ✓ client <-initial- server (2 ms)
      ✓ client has peer error 1 (1 ms)
      ✓ client and server close (3000 ms)
    Ed25519 with custom verify callback
      Ed25519 success with both client and server certificates
        ✓ client connect
        ✓ client dialing (1 ms)
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server
        ✓ client is established (1 ms)
        ✓ client -initial-> server (1 ms)
        ✓ server is established (1 ms)
        ✓ client <-short- server
        ✓ client -short-> server (1 ms)
        ✓ client and server established (1 ms)
        ✓ client close (29 ms)
      Ed25519 success with only server certificates
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client is established
        ✓ client -initial-> server (1 ms)
        ✓ server is established
        ✓ client <-short- server
        ✓ client -short-> server
        ✓ client and server established (1 ms)
        ✓ client close (25 ms)
      Ed25519 fail verifying client with bad client certificate (TlsFail 304)
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client is established
        ✓ client -initial-> server (40 ms)
        ✓ server has local error TlsFail 304
        ✓ client <-short- server (2 ms)
        ✓ client has peer error TlsFail 304
        ✓ client and server close (13 ms)
      Ed25519 fail verifying client with no client certificate (TlsFail 372)
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept
        ✓ client <-initial- server (1 ms)
        ✓ client is established (1 ms)
        ✓ client -initial-> server (2 ms)
        ✓ server has local error TlsFail 372 (1 ms)
        ✓ client <-handshake- server (2 ms)
        ✓ client has peer error TlsFail 372
        ✓ client and server close (14 ms)
      Ed25519 fail verifying server bad server certificate (TlsFail 304)
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (2 ms)
        ✓ client -initial-> server (1 ms)
        ✓ client has local error TlsFail 304 (1 ms)
        ✓ client -short-> server (1 ms)
        ✓ server has peer error TlsFail 304 (1 ms)
        ✓ client and server close (15 ms)

 PASS  tests/native/tls/ecdsa.test.ts (6.919 s)
  native/tls/ecdsa
    ECDSA success with both client and server certificates
      ✓ client connect (3 ms)
      ✓ client dialing
      ✓ client and server negotiation (4 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client is established (1 ms)
      ✓ client -initial-> server (1 ms)
      ✓ server is established
      ✓ client <-short- server (1 ms)
      ✓ client -short-> server (1 ms)
      ✓ client and server established (2 ms)
      ✓ client close (51 ms)
    ECDSA success with only server certificates
      ✓ client connect
      ✓ client dialing (1 ms)
      ✓ client and server negotiation (1 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server
      ✓ client is established (1 ms)
      ✓ client -initial-> server
      ✓ server is established (1 ms)
      ✓ client <-short- server
      ✓ client -short-> server
      ✓ client and server established
      ✓ client close (26 ms)
    ECDSA fail verifying client with bad client certificate (TlsFail 304)
      ✓ client connect (1 ms)
      ✓ client dialing
      ✓ client and server negotiation (1 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (1 ms)
      ✓ client is established
      ✓ client -initial-> server (28 ms)
      ✓ server has local error TlsFail 304
      ✓ client <-handshake- server (2 ms)
      ✓ client has peer error TlsFail 304 (1 ms)
      ✓ client and server close (14 ms)
    ECDSA fail verifying client with no client certificate (TlsFail 372)
      ✓ client connect (1 ms)
      ✓ client dialing
      ✓ client and server negotiation (2 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server
      ✓ client is established (1 ms)
      ✓ client -initial-> server (1 ms)
      ✓ server has local error TlsFail 372
      ✓ client <-handshake- server (2 ms)
      ✓ client has peer error TlsFail 372 (1 ms)
      ✓ client and server close (16 ms)
    ECDSA fail verifying server bad server certificate (TlsFail 304)
      ✓ client connect
      ✓ client dialing (1 ms)
      ✓ client and server negotiation (1 ms)
      ✓ server accept (1 ms)
      ✓ client <-initial- server (2 ms)
      ✓ client has local error TlsFail 304 (1 ms)
      ✓ client -initial-> server (2 ms)
      ✓ server has peer error TlsFail 304
      ✓ client and server close (3000 ms)
    ECDSA fail with no server certificates (InternalError 1)
      ✓ client connect
      ✓ client dialing
      ✓ client and server negotiation (1 ms)
      ✓ server accept (2 ms)
      ✓ server has local error 1
      ✓ client <-initial- server (2 ms)
      ✓ client has peer error 1 (1 ms)
      ✓ client and server close (3000 ms)
    ECDSA with custom verify callback
      ECDSA success with both client and server certificates
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client is established (1 ms)
        ✓ client -initial-> server
        ✓ server is established (1 ms)
        ✓ client <-short- server (1 ms)
        ✓ client -short-> server
        ✓ client and server established (2 ms)
        ✓ client close (29 ms)
      ECDSA success with only server certificates
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server
        ✓ client is established (1 ms)
        ✓ client -initial-> server
        ✓ server is established
        ✓ client <-short- server
        ✓ client -short-> server (1 ms)
        ✓ client and server established
        ✓ client close (26 ms)
      ECDSA fail verifying client with bad client certificate (TlsFail 304)
        ✓ client connect (1 ms)
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client is established
        ✓ client -initial-> server (37 ms)
        ✓ server has local error TlsFail 304
        ✓ client <-short- server (2 ms)
        ✓ client has peer error TlsFail 304
        ✓ client and server close (16 ms)
      ECDSA fail verifying client with no client certificate (TlsFail 372)
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept (1 ms)
        ✓ client <-initial- server (1 ms)
        ✓ client is established
        ✓ client -initial-> server (3 ms)
        ✓ server has local error TlsFail 372
        ✓ client <-handshake- server (2 ms)
        ✓ client has peer error TlsFail 372
        ✓ client and server close (13 ms)
      ECDSA fail verifying server bad server certificate (TlsFail 304)
        ✓ client connect
        ✓ client dialing
        ✓ client and server negotiation (1 ms)
        ✓ server accept
        ✓ client <-initial- server (2 ms)
        ✓ client -initial-> server (2 ms)
        ✓ client has local error TlsFail 304
        ✓ client -short-> server (2 ms)
        ✓ server has peer error TlsFail 304
        ✓ client and server close (16 ms)

Test Suites: 3 passed, 3 total
Tests:       377 passed, 377 total
Snapshots:   0 total
Time:        7.155 s
Ran all test suites matching /.\/tests\/native\/tls/i.
GLOBAL TEARDOWN
```

</details>

**Comment by tegefaulkes** [comment]
OK, updated the general connection logic flow. based on what was discussed above. Everything is slightly cleaner and things clearly happen in stages now.

Stopping is triggered via once events. 
1. a connection error event due to timeout, local or peer error (possibly TLS)
2. a connection stop event due to a graceful closure.

All of these stop triggering events are emitted in `processState` expect for one error due to a socket send problem.

... forgot to hit comment earlier

**Comment by CMCDragonkai** [comment]
Did you move all "state processing" code into `processState`?

You should have a docblock then explains why all relevant code transition happens in this function.

And also document any exceptions to that. Mental model and all that.

**Comment by tegefaulkes** [comment]
`QUICClient` is mostly done now, needs some review and polish but we're in a testable state now.

I'm looking over the tests now.

One thing I've noticed is that a graceful close results in a peer error on the peer connection. So we may have to special case code 0 as no error.

**Comment by CMCDragonkai** [comment]
> One thing I've noticed is that a graceful close results in a peer error on the peer connection. So we may have to special case code 0 as no error.

Yes `0` actually means graceful close. And so that's really not an error at all.

**Comment by CMCDragonkai** [comment]
Note that's true for application error and transport level too.

So a transport level 0 means the transport closed it gracefully.

Application level 0 means application closed it gracefully.

In both cases, not an error.

However it'd be good for the user to be able to read the ending code and message (if any), by exposing this via a function.

I could imagine a handler on stop/stopped that wants to get this information.

**Comment by CMCDragonkai** [comment]
Same idea applies when stream is destroy/destroyed. I'd like to be able to ask about the stream's final code regardless of what it is.

**Comment by CMCDragonkai** [comment]
I can imagine 2 public functions:

```
connection.getError(): { isApp: boolean; code: number; reason: Uint8Array } | undefined;
stream.getError(): number | undefined;
```

**Comment by tegefaulkes** [comment]
The main expectation in tests that has changed is, we don't wait for the peer to finish verifying TLS before considering secure establishment complete.

The main difference here is that a test that expected the connection to start due to the peer rejecting the connection will now see the connection succeed but soon after fail with the TLS error.

These tests should now expect the connection to succeed but soon emit a peer error of 304.


Other problems are likely errors with the code itself. I haven't had a change to tests streams yet so I have no idea on how well that is working right now.

**Comment by CMCDragonkai** [comment]
Hey @tegefaulkes how come you are not calling `this.send(mon);` in `QUICConnection.recv`? I thought that was the plan.

**Comment by CMCDragonkai** [comment]
The `QUICConnection.start` shouldn't be calling `this.send()`.... it does not need to do this, since it's the `QUICClient` and `QUICServer`'s responsibility to do this. The whole point is to just say `await quicConnection.start();`.

And `async public recv` should be calling `this.send(mon)`. Why is this missing, this was like the most important part of our discussion!?

**Comment by CMCDragonkai** [comment]
Still refactoring `QUICConnection` but getting closer.

Made some realisations:

* When calling quiche `conn.recv`, it can set the `peerError()` but it will never throw an exception due to a peer error. It will however throw in response to a `localError()`. Thus one can check for local error in the exception handler, but not peer error.
* The custom TLS verification adds a curve ball to the control flow of `recv` and `send`. Basically if it's not being used and we are infact verifying the peer, then we should be processing the streams as soon as the connection is established. And regular established means secure established. However if it is being used, then first call to `QUICConnection.processStreams` needs to occur instead after the `conn.send` in `QUICConnection.send`. After which, if all the conditions is correct, it will be securely established, and subsequent calls to `processStreams` will occur instead in the `QUICConnection.send`.
* Proved that quiche implementation does not implement stateless reset or any sort of acknowledgement after receiving a `CONNECTION_CLOSE` frame.
* For the `QUICServer` it has to call `QUICConnection.recv` to start the connection, while for the `QUICClient` it has to call `QUICConnection.send` to start the connection. We don't bother exposing the pair of `recv` then `send`, instead `recv` just calls `send`. It might be possible to abstract all of this into the `QUICConnection.start` method later, thus simplifying the logic even further.
* Relevant events for `QUICConnection` include: `EventQUICConnectionError` and `EventQUICConnectionEnd` and `EventQUICConnectionStopped`. These 3 events roughly correspond to `error`, `end` and `close` in regular node's net socket.
* Some interesting exceptions have been created to allow distinction between local errors and peer errors: `ErrorQUICConnectionLocal` and `ErrorQUICConnectionPeer`, these 2 exceptions will be made available into `EventQUICConnectionError.detail`, whereas `EventQUICConnectionEnd` will only have the `peerError()` as the detail.
* Both `EventQUICConnectionEnd` and `EventQUICConnectionError` is handled by `QUICConnection` (thus listening to its own events) and proceeds to: a. reject the start, and b. call stop with force. Rejecting the start is important here in case something is waiting on the `start`. More specifically it rejecting the `secureEstablishedP` promise. However since end is a graceful end, the exception we reject with will be a bit different. Thus when doing `await quicConnection.start()`, you may end up with a `ErrorQUICConnectionRecv`, `ErrorQUICConnectionSend`, `ErrorQUICConnectionLocal`, `ErrorQUICConnectionPeer`... and we will need one just to represent gracefully ending like `ErrorQUICConnectionEnd`.

**Comment by CMCDragonkai** [comment]
In effect, one can just wait for `EventQUICConnectionError` or `EventQUICConnectionStopped`. I don't think it's necessary to listen for `EventQUICConnectionEnd` (although it can be more convenient to find the peer error code).

As long as we expose `connection.getError()` which will give the `peerError` or `localError` whichever one is relevant, then that should work fine.

**Comment by CMCDragonkai** [comment]
So now for `recv` and `send` the only exceptions that get thrown upwards as caller errors are internal errors.

This can occur:

* Failed `this.conn.send` that isn't a `Done`
* Failed `this.conn.recv` that isn't due to a local error
* Failed `QUICSocket.send`

Also possibly processing streams, but I haven't looked at it yet.

This means it calling `send` and `recv` is a bit safer. So now `QUICConnection.start` will also trigger `send` for a client connection, and a `recv` for the server connection.

However I still need to experiment with how these calls will concurrently work with awaiting on `secureEstablishedP` and `abortP`.

I'm thinking that this is actually necessary:

```
Promise.race([
 Promise.all([secureEstablishedP, sendOrRecvP]),
 abortP
])
```

If the `abortP` rejects first, then we need to handle that with a somewhat graceful exit...

If however one of the other rejects first. In the sense that `secureEstablishedP` can reject due to `EventQUICConnectionError` or `EventQUICConnectionEnd`. But `sendOrRecvP` can only reject due to internal errors. But because `EventQUICConnectionError` also is dispatched in those cases, one can argue there's no need to catch any error from `sendOrRecvP`. I'm also somewhat unclear on the exact order of events. It could be that by dispatching events, which then reject promises, that would trigger `secureEstablishedP` to reject first, before errors get thrown upwards to `sendOrRecvP`.

Anyway exception handler of `QUICConnection.start` cannot call `QUICConnection.stop` because they have to be independent, so `QUICConnection.start` has to manage the stopping itself. That means triggering close in a similar way, and then triggering `QUICConnection.send`.

Also note that the `conn.timeout()` will only be non-null upon the first send. So client conn's first send, and server conn's first send too.

**Comment by CMCDragonkai** [comment]
I'm refactoring the conn timeout timer and keepalive timers. Some notes I've made here: https://github.com/MatrixAI/js-timer/issues/5#issuecomment-1712719531

Note the latest changes I've pushed to `js-timer` isn't actually necessary here, they are quality of life improvements. And plus it's only 2.x which is ESM based anyway.

The changes required here would be:

1. Just use `this.connTimeoutTimer?.cancel()`.
2. Take in the `signal: AbortSignal` inside our handler, and check it by doing `if (signal.aborted) return;`, but we also propagate it down to whatever each function calls, which would be `await this.send(undefined, { signal });`.

I just need to check with `js-async-cancellable` that the above call signature is correct.

**Comment by CMCDragonkai** [comment]
@tegefaulkes I don't understand this comment:

```
        // No need to read after creation, doing so will throw during early cancellation
```

What is early cancellation here?

Also if a stream is readable, surely we want to trigger `await quicStream.read();`.

What is being early cancelled here?

**Comment by CMCDragonkai** [comment]
Suppose you mean what if the stream is cancelled early. Ok sure, but then how does a stream get read then if it was not early cancelled... doesn't this delay something?

Shouldn't then early cancellation work even in the case where we run `quicStream.read()`?

**Comment by CMCDragonkai** [comment]
Discovered another issue.

When the connection has max idle timed out, the connection goes straight to being closed. There is no draining phase at all.

And because it is already closed, you cannot then `close(true, 0, Buffer.from('abc'))` as that would throw a `Done` exception.

At the same time, there is no `localError()` nor `peerError()`.

Basically there's no error at all.

So that creates a bit of a problem. I was expecting any if a connection was closed, there would also be either a `localError` or `peerError`. But when a connection is closed due to exhausting the max idle timeout, there's just no error.

We may need to synthetically construct one for our error events and/or the close events.

**Comment by CMCDragonkai** [comment]
This means that there's no connection close frame sent when the connection is timed out.

> If a max_idle_timeout is specified by either endpoint in its transport parameters (Section 18.2), the connection is **silently closed and its state is discarded when it remains idle for longer than the minimum of the max_idle_timeout** value advertised by both endpoints.

**Comment by CMCDragonkai** [comment]
Solved that issue above for now with a new kind of `Close` event.

Also I think naming standard should be extended to be:

* Subject Object Adjective Verb Adverb

Maintains the SOV order, but also puts describing words at the end.

Example: `ErrorQUICConnectionConfigInvalid` instead of `ErrorQUICConnectionInvalidConfig`.

**Comment by CMCDragonkai** [comment]
Events are now:

```
class EventQUICConnectionError extends EventQUICConnection<
  | ErrorQUICConnectionLocal<unknown> // errors that I'm sending to the peer (also due to idle timeout)
  | ErrorQUICConnectionPeer<unknown> // errors that I'm receiving from the peer
  | ErrorQUICConnectionIdleTimeout<unknown>
  | ErrorQUICConnectionInternal<unknown> // other internal errors which means the thing is broken
> {}

class EventQUICConnectionClose extends EventQUICConnection<
  { type: 'local' | 'peer' } & ConnectionError
  |
  { type: 'timeout' }
> {}
```

The order of events is always `error` then `close`.

These flows are possible:

```
// STOP -> ERROR -> CLOSE -> STOPPED
// ERROR -> CLOSE -> STOP -> STOPPED
```

In order to simplify things, the error event is emitted for both connection status errors whether graceful or not, and internal socket errors. I based this functionality off the tcp net socket which emits errors primarily due to internal socket errors, and nothing to do with the remote peer or yourself. It's possible to distinguish the reason by adding 1 event handler and then investigating the class/type of the event detail.

The close event then is emitted to match the `close` event in net socket. It also tells us whether it was a local close, a remote close or idle timeout (where there is no error at all).

I'm still not sure whether one should separate the `error` event. Or maybe even not emit `error` event in the case of a connection status close, and just rely on the close event instead. But for now just left at this stage.

Another interesting thing popped out is that when doing `socket.write()` the tcp socket if it hits an error will both emit the error, and pass it to the callback. The equivalent in our case is rejecting the promise.

However in our case, it only makes sense to reject the promise in the case of an internal error, not due to connection closing errors. So I matched the behaviour here.

Thus one can assume a foundational behaviour similar to net socket events. Where if an error event occurs, a close event will always follow. Just that in our case an error event also means connection status close.

**Comment by CMCDragonkai** [comment]
Now I'm trying to get `QUICStream` to behave the same:

```
class EventQUICStreamError extends EventQUICStream<
  | ErrorQUICStreamLocalRead<unknown> // I may send out errors on both stop sending (shutdown read) and reset stream (shutdown write)
  | ErrorQUICStreamLocalWrite<unknown> // I may send out errors on both stop sending (shutdown read) and reset stream (shutdown write)
  | ErrorQUICStreamPeerRead<unknown> // I may receive errors on both stop sending (shutdown read) and reset stream (shutdown write)
  | ErrorQUICStreamPeerWrite<unknown> // I may receive errors on both stop sending (shutdown read) and reset stream (shutdown write)
  | ErrorQUICStreamInternal<unknown>
> {}

/**
 * QUIC stream readable side was closed
 */
class EventQUICStreamCloseRead extends EventQUICStream<{
  type: 'local' | 'peer';
  code: number;
}> {}

/**
 * QUIC stream writable side was closed
 */
class EventQUICStreamCloseWrite extends EventQUICStream<{
  type: 'local' | 'peer';
  code: number;
}> {}
```

**Comment by tegefaulkes** [comment]
Yes, when timing out there isn't a specific error on `peerError` or `localError`. However there is a flag we can check with `isTimedout`

> 

If I recall, there may be a race condition with cancelling the stream. This would likely cause any `readableController.X()` calls to throw since the stream would've already ended. On reflection the change and comment there is probably not the best. We should have a boolean guarding any stream controller calls withing `QUICstream.read()` or `QUICStream.write()`.

**Comment by CMCDragonkai** [comment]
Thinking about this further, actually we could propagate a push from `QUICConnection` to `QUICSocket`.

The way it would work is similar but it was important to realise the bridging importance of `QUICClient` and `QUICServer`.

So `QUICConnection` pushes events to `QUICClient` or `QUICServer` whichever is the parent to it.

The `QUICClient` and `QUICServer` would then handle this event, and convert it to a "pull" on their `QUICSocket`. This is true whether the `QUICSocket` is encapsulated or shared, it doesn't matter.

Then it is the responsibility of `QUICClient` and `QUICServer` to decide how to deal with the errors from `QUICSocket.send` and it can know that since the `send` occurs through a valid `QUICConnection`, any failure here represents an internal error that therefore leads to shutting down everything.

The `QUICServer` and `QUICClient` would then proceed to force shutdown the `QUICStream`, the `QUICConnection` and the `QUICSocket`. Such a forced shutdown should be passing "internal error codes" down the object hierarchy. That translates to readable streams being cancelled and writable streams aborted with a reason (which means readers get `done: true`, writers get the abortion exception). The connection also gets force closed, but also with an internal error (which would proceed to dispatch a `EventQUICConnectionSend` event, but we would have already removed such a listener). Finally the quic socket gets stopped with an error too, which due to using dgram socket, would mean we just proceed to closing the UDP socket.

Doing such a thing would mean `QUICConnection` and `QUICStream` is completely IO-less. They would be testable without involving an actual udp socket, since all state transitions and changes occurs just through pull methods and push events.

---

Note that dgram sockets don't have an equivalent `.destroy(error)` function like net sockets do. Errors can be send-specific... so actually even if a send were to fail, it doesn't necessarily mean the next send would fail. It could be an intermittent failure. That actually means we may not need to be so strict on a failed `this.socket.send` call. We could just log out the error and proceed. The `QUICConnection` would be maintaining state, and if the socket send failed, it would eventually retry and resend such data. See in the dgram docs, an error event doesn't automatically mean a subsequent close event. And if no data can be sent, eventually max idle timeout will happen.

On the other hand, we use `this.socket.send` when negotiating a new connection. And if it fails at any point, we end up shutting down everything too. I wonder... if we should be loose or strict about this? We could also just ignore the connection negotiation if the `this.socket.send` didn't work.

**Comment by CMCDragonkai** [comment]
I've refactored the `QUICStream` `ReadableStream` and `WritableStream` sides.

For now all the logic is inside each step stream to avoid too much complexity spread.

Todo:

* Refactor the `QUICStream.read` and `QUICStream.write` functions that unpauses the writable side and readable side.
* Refactor the `QUICStream.closeRecv` and `QUICStream.closeSend`...

The dummy data writes look kind of weird. What's the usage of `dummy data` @tegefaulkes?

With the way streams are done right now. We always dispatch error and close events. When `write` is called the whole idea is to unpause the `writableP` by resolving it if the function exists.

I don't think it's necessary to check if the stream is actually writable, that should be done inside the web stream.... which it is all done inside now.

**Comment by CMCDragonkai** [comment]
I believe simply:

```
public write(): void {
  this.resolveWritableP?.();
}
```

Is sufficient.

**Comment by CMCDragonkai** [comment]
Even for `read` this is fine:

```
public read(): void {
  this.resolveReadableP?.();
}
```

I don't understand what the rest of the code was for...?

**Comment by CMCDragonkai** [comment]
I think `QUICStream` is well refactored. Time to fix up the rest of the stuff, and propagate `EventQUICStreamSend` and `EventQUICConnectionSend`.

**Comment by CMCDragonkai** [comment]
So I ended up factoring out the `readable.cancel` and `writable.abort` back into a shared protected method like before, so it ends up being callable by both `readable.cancel`, `writable.abort` and `QUICStream.cancel`.

Force cancellation of the quic streams from outside of the readers/writers is tricky because if there are existing readers/writers that are locked on the stream, then you cannot just call `readable.cancel` and `writable.abort`. Using `this.readableController.error` and `this.writableController.error` also doesn't work because it doesn't clean up the underlying quiche state.

So we have `protected readableCancel` and `protected writableAbort` that ends up doing this duty for both internal cancel and abort, and `QUICStream` level force cancellation.

**Comment by CMCDragonkai** [comment]
It was also important to ensure that `QUICStream.cancel` does not in fact throw any errors up too. So I remove the `throw e;` in `readableCancel` and `writableAbort`.

**Comment by CMCDragonkai** [comment]
Unidirectional streams is now supported. Basically depending on the unidirectional direction, the `QUICStream` may have its readable or writable automatically closed upon creation. I had to do this because it was getting awkward handling unidirectional streams in case another QUIC protocol was interacting with it. It ended up being cleaner anyway to support it.

`QUICConnection` now pushes events upwards using `EventQUICConnectionSend`.

This was originally in QUICConnection. It needs to be moved to `QUICClient` and `QUICServer`.

```
      try {
        await this.socket.send(
          sendBuffer,
          0,
          sendLength,
          sendInfo.to.port,
          sendInfo.to.host,
        );
      } catch (e) {
        const e_ = new errors.ErrorQUICConnectionInternal(
          'Failed to send data on the QUICSocket',
          {
            data: {
              msg: sendBuffer,
              offset: 0,
              length: sendLength,
              host: sendInfo.to.host,
              port: sendInfo.to.port,
            },
            cause: e,
          }
        );
        // This is a software error
        this.conn.close(
          false,
          ConnectionErrorCode.InternalError,
          Buffer.from('')
        );
        this.dispatchEvent(
          new events.EventQUICConnectionError({ detail: e_ })
        );
        this.dispatchEvent(new events.EventQUICConnectionClose(
          {
            detail: {
              type: 'local',
              ...this.conn.localError()!
            }
          }
        ));
        throw e_;
      }
```

**Comment by CMCDragonkai** [comment]
Interesting notes... you are listening on a push event from an encapsulated object, and this leads you perform an internal pull call (essentially an asynchronous state transition), then you should in fact drop errors by doing `await this.doSomethingAsync().catch(() => {});` in case of caller errors.

This is because is your own internal handler of an encapsulated event. Caller errors have to be dropped there.

Instead you rely on the domain error transition, thus your own evented object will just dispatch the necessary error events inside the callstack of `this.doSomethingAsync`.

Not sure what you'd call this, but it's like you're subscribed to something and doing pull calls internally, you don't want caller errors to bubble up to become an unhandled promise rejection when your domain errors will eventually be dispatched.

**Comment by CMCDragonkai** [comment]
The `QUICServer` is now bridging events from `EventQUICConnectionSend` to `QUICSocket`.

Now the issue is between `QUICServer` and `QUICSocket`. They are still mutually calling each other.

If we were to break mutual dependency, it would make sense for `QUICSocket` to dispatch events to the `QUICServer` instead.

However this complicates things because the `QUICSocket` is shared between many `QUICClient`. So any dispatch event would be inefficiently broadcasting function calls.

I came up with an idea so that `QUICSocket` would instead dispatch specific events to each client or server depending on a the connection ID. However I think it's a radical departure from the usage of `QUICConnectionMap`.

So for now I think it should be ok for `QUICSocket` and `QUICServer` to be tightly integrated where they have mutual recursion. We just need to manage errors from both together whenever a call occurs. Generally speaking, control flow always starts from `QUICSocket.handleSocketMessage`. That will call `QUICServer.acceptConnection`, which will then end up calling `QUICSocket.send`. Thus all exceptions bubble up to the `handleSocketMessage` as the root control flow point.

**Comment by CMCDragonkai** [comment]
Ok I think the architecture is finally refactored to support push flows properly.

Testing is needed @tegefaulkes can you join in and help here? Lots of commentary required and bug checking.

**Comment by CMCDragonkai** [comment]
Task 4 is achieved by using `EventAll` in `QUICConnection`, `QUICServer`, `QUICClient`.

**Comment by CMCDragonkai** [comment]
Discussion about mutual recursion between QUICServer and QUICSocket (and QUICConnection)

<details>

image

</details>

**Comment by CMCDragonkai** [comment]
@tegefaulkes 

Linting commits should only be done in 2 places:

1. With any specific commit
2. At the end of the PR

Otherwise, the linting commits break git blame and it's difficult to know what the sequence of things are. Now I can't always do 1. because I'm also pushing up commits with intermediate broken code.

**Comment by tegefaulkes** [comment]
I do linting with every commit. even with broken code since it still works fine, you just need to ignore the warnings. So i'd prefer it if we do linting for every commit.

**Comment by tegefaulkes** [comment]
As for the utils.

`extractSocket` Extracts the socket out of a `QUICServer` or `QUICClient` and adds it to an array. An `afterEach` iterates over all the sockets and forces them to close. This is a fail-safe for making sure tests don't hold the process open since an active socket will do that. It's mainly to prevent the tests from never ending if they fail and skip clean up. Otherwise CI will take an hour to end if a socket wasn't closed.

`handleStreamProm` A utility for do something in the background. Used to handle streams gracefully without a whole bunch of boilerplate. Will take a stream, read it until it ends while concurrently writing the data you provided. It will insure that the stream is fully cleaned up if it otherwise fails. Will also log the results.

`waitForTimeoutNull` In a while loop will wait the delay returned by `conn.timeout()` until it returns `null`. Calls `onTimeout()` at each step. Used mostly to trigger a state change in the native connection tests. 

`connStats` Just prints out a bunch of useful information about connections. Not used currently but was used a bunch when exploring what exactly changed about the connection.

`generateConfig` generates a TLS config of a certain key type. used everywhere in tests since server connection require a config.

`createReasonConverters` Creates a matching pair of `reasonToCode` and `codeToReason` arrow functions. `reasonToCode` will store the reason in a map and return an incrementing code. `codeToReason` will retrieve the reason from the map with the given code. Allows us to seamlessly see what reason caused an error for the stream or connection.

**Comment by CMCDragonkai** [comment]
Seems like both `handleStreamProm` and `extractSocket` is similar. I think it would better to abstract the entire concept to a killSockets fixture. Something you'd use and apply all relevant sockets as an array and it would actually execute `afterEach` or just `afterAll`?

**Comment by tegefaulkes** [comment]
`handleStreamProm` is pretty different. It's just gracefully handling the streams as a promise you can await later. It prevents a whole bunch of boiler plate, especially in the concurrency testing.

`extractSocket` is different in that it's just getting the protected socket property from the client or server. We just destroy them in the `afterEach` peferibly or the `AfterAll`.

File: src/QUICConnection.ts [hunk 2]
```diff
@@ -410,73 +335,180 @@ class QUICConnection extends EventTarget {
...
+    this.addEventListener(
+      events.EventQUICConnectionError.name,
+      this.handleEventQUICConnectionError,
+    );
+    this.addEventListener(
+      events.EventQUICConnectionClose.name,
+      this.handleEventQUICConnectionClose,
+      { once: true }
     );
+    this.addEventListener(EventAll.name, this.handleEventQUICStream);
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:511]: We're registering `handleEventQuicStream` to all the `QUICConnection` events. This should only be added to the `QUICStream` events right?

Since the `handleEventQUICStream` is cloning all events, we're getting an infinite event loop and running into the max stack size.

I'm disabling for now, The handler should be applied to the `QUICStreams ` once they're created.

File: src/QUICConnection.ts [hunk 3]
```diff
@@ -410,73 +335,180 @@ class QUICConnection extends EventTarget {
...
+    } finally {
+      ctx.signal.removeEventListener('abort', abortHandler);
+    }
+    if (this.config.keepAliveIntervalTime != null) {
+      this.startKeepAliveIntervalTimer(this.config.keepAliveIntervalTime);
+    }
+    this.addEventListener(
+      events.EventQUICConnectionError.name,
+      this.handleEventQUICConnectionError,
+    );
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:505]: the `handleEventQUICConnectionError` is the main way of rejecting the `this.secureEstablishedP`. But it's only added to the listener *after*  awaiting `this.secureEstablishedP`. As a result, the `QUICConnection.start()` is not reacting to most connection errors including the idle timeout and is hanging.

File: src/QUICConnection.ts [hunk 4]
```diff
@@ -515,507 +545,753 @@ class QUICConnection extends EventTarget {
...
-      }
     }
+    // If `config.verifyCallback` is not defined, simply being established is
+    // sufficient to mean we are securely established, however if it is defined
+    // then secure establishment occurs only after custom TLS verification has
+    // passed.
+    if (this.conn.isEstablished() && this.config.verifyCallback != null) {
+      this.resolveSecureEstablishedP();
+    }
+    // If we are "secure established" we can process streams.
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:827]: Logic error, if the  `this.config.verifyCallback` is *not* defined then we resolve.

File: src/QUICConnection.ts (hunk 2 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts:511]: Yes this should have been registered to the quic stream.

There are 2 places to do it, one on `newStream` and another on `processStreams`.

The removal of the handler will occur on the `EventQUICStreamDestroyed`.

File: src/QUICConnection.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts:505]: Yep, the general principle should be to:

* Add event listeners BEFORE async operations begin.
* Remove event listeners AFTER async operations finish.

This translates roughly to adding event listeners at the beginning of `start` and removing them at the end of the `stop`.

For `create` and `destroy`, it's sort of depends. Firstly you can only register handlers after the instance is constructed, otherwise you cannot access them. But also you would do at the end of destroy. However for dependencies that are asynchronously created it depends on the other of async operations. See `QUICClient.createQUICClient`, it's a bit complicated.

File: src/QUICConnection.ts (hunk 2 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: This is now fixed with b9d1212de609c88c0f2a9c595cb6037f178bae13.

File: src/QUICConnection.ts (hunk 3 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: This should be fixed by 5865ec86b261e00144901cf1869a16941e05e9de.

File: src/QUICConnection.ts (hunk 4 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Yes, so the current fix ensures that if `verifyCallback` is set, then it will run the check under `send`, and if it isn't set, it will resolve the `secureEstablishedP` if the connection passed establishment.

**Comment by CMCDragonkai** [comment]
> `handleStreamProm` is pretty different. It's just gracefully handling the streams as a promise you can await later. It prevents a whole bunch of boiler plate, especially in the concurrency testing.
> 
> `extractSocket` is different in that it's just getting the protected socket property from the client or server. We just destroy them in the `afterEach` peferibly or the `AfterAll`.

The `handleStreamProm` should be called `flushQUICStreamP` - give it a big comment explaining that it is flushing both readable and writable until graceful close.

The `extractSocket` should be turned into a factory function that is executed on the `beforeEach` and the returned deallocator is called on the `afterEach`. This pattern we have done before for PK agent process lifecycle testing.

**Comment by CMCDragonkai** [comment]
TODO:

1. QUIC socket failed send should not result in domain error - @CMCDragonkai 
2. `QUICConnection.test.ts` and `QUICClient.test.ts` and `QUICServer.test.ts` and `QUICStream.test.ts` are all integration tests - that means their fixtures just setup the client and server, but their tests/expectations focus-in on their specification objects, so `QUICConnection.test.ts` might use nested describes to create different client/server scenarios, and then their tests would focus on the lifecycle of the `QUICConnection` and test different kinds of starting and stopping and closing scenarios. - @tegefaulkes

File: src/QUICConnection.ts [hunk 5]
```diff
@@ -515,505 +549,762 @@ class QUICConnection extends EventTarget {
...
-          void this.stop({ force: true });
-        }
-        logger.debug('CLEANING UP TIMER');
         return;
       }
-
-      // There may be data to send after timing out
-      void this.send();
-
+      // Otherwise, we should be calling send after the timeout
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:1168]: We shouldn't return after closing here. If it closed due to the connections timing out from the `maxIdleTimeout` then we need to dispatch the error and close event.

Comment (tegefaulkes) [reply src/QUICConnection.ts:1168]: Oh wow, the diff is really bad here. In any case, we should be checking if the connection timed out here rather than later.

File: src/QUICConnection.ts [hunk 6]
```diff
@@ -410,73 +339,180 @@ class QUICConnection extends EventTarget {
...
+            }
+          })
+        );
+      }
+      // Wait for the connection to be fully closed
+      // It is expected that max idle timer will eventually resolve this
+      await this.closedP;
+      // Throw the augmented exception if it is augmented
+      // Otherwise throw the original
+      throw e_;
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:509]: This is throwing the `ErrorQUICConnectionLocal` with the original error as the cause. It makes more sense to throw the original error here rather than the derived one. the `ErrorQUICConnectionLocal` still makes sense for dispatching the error event.

In terms of usage, if the connection or client creation timed out due to timeout or ctx signal abortion. I'd rather get their specific errors thrown back up.

File: src/QUICClient.ts [hunk 7]
```diff
@@ -169,287 +156,399 @@ class QUICClient extends EventTarget {
...
+      socket,
+      remoteInfo: {
+        host: host_,
+        port: port_,
+      },
+      config: quicConfig,
+      reasonToCode,
+      codeToReason,
+      logger: logger.getChild(`${QUICConnection.name} ${scid.toString()}`),
+    });
```
Comment (tegefaulkes) [inline src/QUICClient.ts:214]: Constructing the `QUICConnection` can throw an `ErrorQUICConnectionConfigInvalid` error. In this case we have a resource leak as we wont clean up the `QUICSocket`.

Comment (CMCDragonkai) [reply src/QUICClient.ts:214]: Proceed to catch and stop the socket if it isn't shared.

**Comment by CMCDragonkai** [comment]
With node 20 you cannot do `globalThis.crypto = ...` it just doesn't work.

So I've removed that from `tests/utils.ts`.

Also due to jest globals, it's not possible to use `tests/utils` inside `benches`, so instead I've used `benches/suites/utils.ts`.

The `benches` is now matching the structure that is in `Polykey` that @amydevs is using in js-ws too.

I've also rewritten the `generateConfig` into `generateTLSConfig` and you should copy that over instead of using `generateConfig` in `tests/utils.ts` @tegefaulkes. This is in `benches/suites/utils.ts`.

Atm, the benchmarks isn't working. I'm getting something like this:

```
[nix-shell:~/Projects/js-quic]$ npm run bench

> @matrixai/quic@0.0.21 bench
> rimraf ./benches/results && ts-node ./benches

Running "streams.stream_1KiB" suite...
>>>>>>>>> HANDLING THE QUIC SERVER STREAM
Progress: 100%

  send 1Kib of data over QUICStream:
    685 ops/s, ±11.33%   | fastest

Finished 1 case!

Saved to: /home/cmcdragonkai/Projects/js-quic/benches/results/streams/stream_1KiB.json

Saved to: /home/cmcdragonkai/Projects/js-quic/benches/results/streams/stream_1KiB.chart.html

Saved to: /home/cmcdragonkai/Projects/js-quic/benches/results/streams/stream_1KiB_metrics.txt
ERROR:stream_1KiB Bench:ErrorQUICConnectionLocal: QUIC Connection local error - Stopping connection due to local error
ERROR:stream_1KiB Bench.QUICConnection 55c518844f342ef6ed8028f8f9df968fb6e5c59c:ErrorQUICConnectionLocal: QUIC Connection local error - Stopping connection due to local error
^C
```

There's a few issues:

1. It's so freaking slow!
2. It's not properly cleaning up quic streams, it seems there's an error with closing either the stream or the connection, either way the bench doesn't terminate.
3. The benchmarks unfortunately don't really have a teardown function that can work, we only have an initial setup. This complicates things...

File: src/QUICClient.ts (hunk 7 above)
Comment (CMCDragonkai) [reply src/QUICClient.ts]: Done in a3bd8016662ef2b45ec10370dcd6e7e494f3ae77

File: src/QUICConnection.ts [hunk 8]
```diff
@@ -515,505 +549,762 @@ class QUICConnection extends EventTarget {
...
+    // If the timer is settled, create it
+    // If the timer is settling, do nothing (it will recreate itself)
+    // If the timer is null, reset it
+    // Plus 1 to the `timeout` to compensate for clock de-sync between JS and Rust
     if (
-      this.connTimeOutTimer != null &&
-      this.connTimeOutTimer.status === null
+      this.connTimeoutTimer == null ||
+      this.connTimeoutTimer.status === 'settled'
     ) {
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:1235]: This condition doesn't re-create the timer after it has settled but not re-created itself. 

In that case the `connTimeoutTimer` exists but `connTimeoutTimer.status` is `null`. I'd expect it to be `'settled'` but I'm not sure why it's null. A bug in the timer implementation?

In any case, A quick fix solution is to delete the `this.connTimeoutTimer` when the timer has ended for whatever reason.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1280]: This was done in 4e354752ae6281861c20ded1dc7334b0b0e276d4, we only needed to delete the timer when the timer is cancelled.

I think in the long run, the timer status should probably have: `settling | settled | cancelled | null`.

The `null` currently means both the timer hasn't executed yet and is still null when the timer is cancelled.

I might make the update first then apply it here, since in the long run, having a separate status for cancelled timer is a good thing.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1280]: Actually I just ran tests in `js-timer`, and I have found that after cancellation, the timer is rejected, and after rejection, the timer is `settled`.

So `settled` can mean resolution or rejection, and cancellation and abortion both mean eventually rejection.

Thus it is not correct to assume that after cancellation the status will be `null`, it depends on how much time passes. Immediately afterwards, it's set to `null`, but eventually it will reject and become `settled`.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1280]: Actually I just tested again:

```
      const t1 = new Timer(undefined, 100);
      console.log(t1.status);
      t1.cancel();
      console.log(t1.status);
```

And we can see that after `t1.cancel()` it is immediately `settled`.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1280]: So that fix if `delete this.connTimeoutTimer` is not necessary.

Because if it were in fact cancelled, then `this.connTimeoutTimer.status` would be `settled`.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1282]: I reverted that change in 4d3c9e2280e8e2cf8f2f2f48dacb039b874c2d35

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1282]: Can you re-check the condition you think is happneing here?

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1282]: So the fix is doing something... without it, indeed the QUICConnection is not stopping. However it should not be necessary. I still get errors somewhere, so I think something else is at fault here.

**Comment by CMCDragonkai** [comment]
@amydevs Found the reason why I couldn't import from `tests/utils.ts`. It's because I was using:

```
import { fc } from '@fast-check/jest';
```

I changed to using:

```
import fc from 'fast-check';
```

Now I can import from `tests/utils.ts`. That keeps it simple.

**Comment by CMCDragonkai** [comment]
I've moved `generateTLSConfig` back into `tests/utils.ts` @tegefaulkes please switch over to using it and remove `generateConfig` and associated types.

**Comment by CMCDragonkai** [comment]
Ok I got a working script here. It seems that if things are closed/destroyed too quickly we're getting some weird errors. It was required to put the `await testsUtils.sleep(1000);` there to allow it all gracefully finish.

<details>

```
import Logger, { LogLevel, StreamHandler, formatting } from '@matrixai/logger';
import QUICClient from './src/QUICClient';
import QUICServer from './src/QUICServer';
import * as events from './src/events';
import * as utils from './src/utils';
import * as testsUtils from './tests/utils';

async function main() {
  const logger = new Logger(`stream_1KiB Bench`, LogLevel.INFO, [
    new StreamHandler(
      formatting.format`${formatting.level}:${formatting.keys}:${formatting.msg}`,
    ),
  ]);
  const data1KiB = Buffer.alloc(1024);
  const tlsConfig = await testsUtils.generateTLSConfig('RSA');
  const quicServer = new QUICServer({
    config: {
      verifyPeer: false,
      key: tlsConfig.leafKeyPairPEM.privateKey,
      cert: tlsConfig.leafCertPEM,
    },
    crypto: {
      key: await testsUtils.generateKeyHMAC(),
      ops: {
        sign: testsUtils.signHMAC,
        verify: testsUtils.verifyHMAC,
      },
    },
    logger: logger.getChild('QUICServer'),
  });
  quicServer.addEventListener(
    events.EventQUICServerConnection.name,
    // @ts-ignore
    (evt: events.EventQUICServerConnection) => {
      const connection = evt.detail;
      connection.addEventListener(
        events.EventQUICConnectionStream.name,
        // @ts-ignore
        async (evt: events.EventQUICConnectionStream) => {
          const stream = evt.detail;
          // Graceful close of writable
          process.stderr.write('>>>>>>>>> HANDLING THE QUIC SERVER STREAM\n');
          await stream.writable.close();
          // Consume until graceful close of readable
          for await (const _ of stream.readable) {
            // Do nothing, only consume
          }
          process.stderr.write('<<<<<<<< HANDLED THE QUIC SERVER STREAM\n');
        }
      );
    }
  );
  await quicServer.start();
  const quicClient = await QUICClient.createQUICClient({
    host: utils.resolvesZeroIP(quicServer.host),
    port: quicServer.port,
    config: {
      verifyPeer: false,
    },
    crypto: {
      ops: {
        randomBytes: testsUtils.randomBytes,
      },
    },
    logger: logger.getChild('QUICClient'),
  });

  const stream = await quicClient.connection.newStream();
  const reader = stream.readable.getReader();
  const writer = stream.writable.getWriter();

  for (let i = 0; i < 1000; i++) {
    await writer.write(data1KiB);
  }

  // This should already be done, because it was closed
  await reader.cancel();

  await writer.close();

  await testsUtils.sleep(1000);

  process.stderr.write('BEFORE QUICCLIENT DESTROY\n');

  // No need to force, streams should already be closed
  // If your force is true by default, then we are technically force closing streams
  // It will cause an error
  await quicClient.destroy({ force: false });

  process.stderr.write('DESROYED\n');

  // If the connections are all gone, we shouldn't need to do this
  await quicServer.stop({ force: false });
}

void main();
```

</details>

This produces a log like:

<details>

```
INFO:stream_1KiB Bench.QUICServer:Start QUICServer on [::]:0
INFO:stream_1KiB Bench.QUICServer.QUICSocket:Start QUICSocket on [::]:0
INFO:stream_1KiB Bench.QUICServer.QUICSocket:Started QUICSocket on [::]:34198
INFO:stream_1KiB Bench.QUICServer:Started QUICServer on [::]:34198
INFO:stream_1KiB Bench.QUICClient:Create QUICClient to [::1]:34198
INFO:stream_1KiB Bench.QUICClient.QUICSocket:Start QUICSocket on [::]:0
INFO:stream_1KiB Bench.QUICClient.QUICSocket:Started QUICSocket on [::]:54495
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6:Connect QUICConnection
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6:Start QUICConnection
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5:Accept QUICConnection
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5:Start QUICConnection
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6:Started QUICConnection
INFO:stream_1KiB Bench.QUICClient:Created QUICClient to [::1]:34198
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6.QUICStream 0:Create QUICStream
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6.QUICStream 0:Created QUICStream
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5:Started QUICConnection
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5.QUICStream 0:Create QUICStream
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5.QUICStream 0:Created QUICStream
>>>>>>>>> HANDLING THE QUIC SERVER STREAM
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6.QUICStream 0:Destroy QUICStream
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6.QUICStream 0:Destroyed QUICStream
<<<<<<<< HANDLED THE QUIC SERVER STREAM
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5.QUICStream 0:Destroy QUICStream
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5.QUICStream 0:Destroyed QUICStream
BEFORE QUICCLIENT DESTROY
INFO:stream_1KiB Bench.QUICClient:Destroy QUICClient
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6:Stop QUICConnection
ERROR:stream_1KiB Bench.QUICClient:ErrorQUICConnectionLocal: QUIC Connection local error - Stopping connection due to local error
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5:Stop QUICConnection
INFO:stream_1KiB Bench.QUICClient.QUICConnection 7d8d5d89f3bfd6c270ea04d2f8bca50d9d2720a6:Stopped QUICConnection
INFO:stream_1KiB Bench.QUICClient.QUICSocket:Stop QUICSocket on [::]:54495
INFO:stream_1KiB Bench.QUICClient.QUICSocket:Stopped QUICSocket on [::]:54495
INFO:stream_1KiB Bench.QUICClient:Destroyed QUICClient
DESROYED
INFO:stream_1KiB Bench.QUICServer:Stop QUICServer on [::]:34198
INFO:stream_1KiB Bench.QUICServer.QUICConnection cd739e144eaee22eef767da287daa6e8208552d5:Stopped QUICConnection
INFO:stream_1KiB Bench.QUICServer.QUICSocket:Stop QUICSocket on [::]:34198
INFO:stream_1KiB Bench.QUICServer.QUICSocket:Stopped QUICSocket on [::]:34198
INFO:stream_1KiB Bench.QUICServer:Stopped QUICServer on [::]:34198
```

</details>

**Comment by CMCDragonkai** [comment]
Reworking some of the error/info messages. I'm seeing this in my prototyping `test.ts`:

```
2023-09-15T15:27:47.185Z-INFO:stream_1KiB Bench.QUICClient.QUICConnection 200a7de2649389ae3a0e6149352171866ee82181:Stop QUICConnection
2023-09-15T15:27:47.185Z-INFO:stream_1KiB Bench.QUICClient.QUICConnection 200a7de2649389ae3a0e6149352171866ee82181:ErrorQUICConnectionLocal: QUIC Connection local error - Locally closed with application code 0
2023-09-15T15:27:47.187Z-INFO:stream_1KiB Bench.QUICServer.QUICConnection 7cf3039e8cc2aa6fc7ab4785a625c2aa54956b03:ErrorQUICConnectionPeer: QUIC Connection peer error - Peer closed with application code 0
2023-09-15T15:27:47.188Z-INFO:stream_1KiB Bench.QUICServer.QUICConnection 7cf3039e8cc2aa6fc7ab4785a625c2aa54956b03:ErrorQUICConnectionPeer: QUIC Connection peer error - Peer closed with application code 0
2023-09-15T15:27:47.188Z-INFO:stream_1KiB Bench.QUICServer.QUICConnection 7cf3039e8cc2aa6fc7ab4785a625c2aa54956b03:Stop QUICConnection
```

You can see here that the there are 2 of them:

```
2023-09-15T15:27:47.187Z-INFO:stream_1KiB Bench.QUICServer.QUICConnection 7cf3039e8cc2aa6fc7ab4785a625c2aa54956b03:ErrorQUICConnectionPeer: QUIC Connection peer error - Peer closed with application code 0
2023-09-15T15:27:47.188Z-INFO:stream_1KiB Bench.QUICServer.QUICConnection 7cf3039e8cc2aa6fc7ab4785a625c2aa54956b03:ErrorQUICConnectionPeer: QUIC Connection peer error - Peer closed with application code 0
```

It's a repitition of the error message.

Now this message can only come from one place under the `QUICConnection.send`. I believe repeated calls to `QUICConnection.send` while it is not stopping will basically result in this error message and multiple dispatches of this event.

Now since this is on the `QUICServer`, nothing is calling `QUICConnection.stop` yet because this is being stopped from the client first.

This was fixed in 5e5405e3b9117ef10bc156da29d2e8cf7c39a622

File: src/QUICConnection.ts (hunk 8 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts:1239]: I've actually re-enabled this change. However I don't think this is accurate. It need sto be checked again as why this is happening.

In general, it appears the code is not robust against immediate closures/destructions. It gets into a bad state, but not sure what that is yet.

The code does work fine as long as things are timed well.

File: src/QUICConnection.ts (hunk 6 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Ok this is fine. Already done in ed97908f546872d61b33dc7e874f5c3437bf8acc

File: src/QUICConnection.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: What was this?

**Comment by CMCDragonkai** [comment]
A few optimisations:

1. Remove monitor in favour of a single lock that is applied on the `recv` call. Because it is now chained to the `send`, it's possible to only force mutual exclusion on the `recv` and `send` combo. The only reason is to prevent another `recv` running the middle before `send` is called. (Even this might not be needed, we will need to see) - This improves it from 700 ops/s to 1000 ops/s.
2. Removal of the `resolveHost` in the `QUICSocket.send`. This I've decided to keep, it does not change the performance at all because `resolveHost` does not try look up via DNS if the address is not a hostname. So it has no effect.

**Comment by CMCDragonkai** [comment]
To address `2.`, I created an `@internal` `send_` that can be used without the additional checks `this.socket.send_`. So that way the external `this.socket.send` still does all the checks since the checks is unnecessary for internal sends.

**Comment by CMCDragonkai** [comment]
Some extra ideas:

1. Investigate with `recv` and `send` locking is needed at all. Maybe it's not a bad idea to allow another `recv` to run in between before `send`.
2. Investigate if `send` can be coalesced if multiple areas of `send` are adding up to each other.
3. Investigate how much of `recv` and `send` can be just synchronous...?

**Comment by CMCDragonkai** [comment]
I've changed the both send and recv config default sizes to be `1350` as per the examples in quiche.

File: src/QUICConnection.ts (hunk 8 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts:1229]: There are some concurrent close operations that don't seem to work well when things happen too quickly. Plus this comment still needs investigation since this shouldn't be a problem.

**Comment by CMCDragonkai** [comment]
Regarding 1. and 2., it seems it should be possible to have `recv`, `send` and `processStreams` entirely synchronous.

Here's why:

1. The sole reason why all of these are asynchronous is primarily because they infect each other with asynchronousness.
2. There are only 2 root asynchronous operations:
   * `await this.config.verifyCallback`
   * `await stream.writable.close()`

For the `verifyCallback` we can remove the ability for it to be asynchronous. It seems easy enough that checking against the certificates can be a synchronous function with any checks done entirely synchronously.

For `await stream.writable.close()` it is entirely an artifact of writable stream and for supporting unidirectional streams.

If we wanted to simply do it all synchronously, we could simply initiate error out on the `writable`, this actually makes more sense, as we cannot gracefully close a writable stream if it's unidirectional.

If we refactor this a bit, this would change the `QUICStream` to be entirely synchronous. Which is to say, there's no need to have an asynchronous creation function at all. We can remove `createQUICStream` and instead stick with a regular constructor with a `destroy` method.

That would then remove the recv lock too. And then calling `recv` which then calls `send` and any intermediate `processStreams` can be entirely synchronous.

And if it is entirely synchronous, it would also be possible to entirely coalesce calls to `QUICConnection.send`.

**Comment by CMCDragonkai** [comment]
It's possible to make `WritableStream` closed synchronously if I use `controller.error` at the beginning. I think that's more correct for unidirectional streams. I just need a special exception to indicate when something was never created due to being unidirectional.

```ts
const writableStream = new WritableStream({
  start(controller) {
    controller.error(new Error('LOL'));
  },
  write(chunk) {
    console.log(`Received chunk: ${chunk}`);
  },
  abort(reason) {
    console.log(`Stream aborted, reason: ${reason}`);
  },
});

const writer = writableStream.getWriter();

async function main() {
  console.log('LOL');
  try {
    await writer.close();
  } catch(e) {
    console.log('CLOSE', e.message);
  }
  try {
    console.log(await writer.closed);
  } catch(e) {
    // Closed turns into error
    console.log('CLOSED', e.message);
  }
  try {
    await writer.ready;
  } catch(e) {
    console.log('READY', e.message);
  }
  try {
    await writer.abort();
    console.log('SUCCEEDS');
  } catch (e) {
    console.log('ABORT', e.message);
  }
  console.log('DONE');
}

void main();
```

**Comment by CMCDragonkai** [comment]
Note that the exception passed into `controller.error` is returned as part of awaiting for `closed` or `ready` or even the initial `close()` operation.

However once the stream is in fact closed... that exception is dropped, and instead we get a `TypeError: Invalid state: WritableStream is closed`.

That means when interacting with streams, it's possible to directly acquire the original reason exception... but afterwards once it is closed, you will only get the native `TypeError: Invalid state: WritableStream is closed` exception.

This is ok, since when interacting with streams, you'll always get your custom exception first... before the stream actually closes and thus you lose that exception and you get the native `TypeError`.

I suspect this is the same behaviour for `ReadableStream` too...

Of course I close my readable stream for unidirectional streams, thus you don't actually get an error trying to read from it, you just end up getting `done: true` all the time.

**Comment by CMCDragonkai** [comment]
Actually I realise once it is unidirectional to make sure both streams perform symmetrically, it's better to instead throw errors into both streams.

See:

```ts
const readableStream = new ReadableStream({
  start(controller) {
    controller.error(new Error('LOL'))
  },
});

const writableStream = new WritableStream({
  start(controller) {
    controller.error(new Error('LOL'));
  },
});

const reader = readableStream.getReader();

const writer = writableStream.getWriter();

async function main() {

  try {
    const r = await reader.read();
    console.log(r);
  } catch (e) {
    console.log('READ', e.name, e.message);
  }

  try {
    const r = await reader.read();
    console.log(r);
  } catch (e) {
    console.log('READ', e.name, e.message);
  }

  try {
    await writer.write(Buffer.from('abc'));
  } catch (e) {
    console.log('WRITE', e.name, e.message);
  }
  try {
    await writer.write(Buffer.from('abc'));
  } catch (e) {
    console.log('WRITE', e.name, e.message);
  }

}

void main();

// Output:
// READ Error LOL
// READ Error LOL
// WRITE Error LOL
// WRITE Error LOL
```

**Comment by CMCDragonkai** [comment]
Removed all asynchronicity, now everything runs synchronously but for a single stream. Now from 1000 ops/s to 1248 ops/s a big improvement, but so much slower than js-ws.

I'm beginning to think this isn't about the JS code, there's something else that is slow.

Maybe it's UDP, maybe it's the native FFI, maybe it's something that quiche is doing perhaps it is doing some sort of congestion limitation...?

@amydevs thoughts?

**Comment by CMCDragonkai** [comment]
Even after changing the max stream size, it doesn't do anything, still stays the same speed.

Ok we're going to need to do a few things:

1. Establish a baseline - first by just testing the baseline speed of node's dgram socket
2. Then establish a baseline of just using `quiche` directly (this may require a bit of setup)
3. Then compare it against the stream writes.

If there's significant difference, the next step is bring a tracer to and flamegraph this thing!

**Comment by tegefaulkes** [comment]
In regards to making `QUICStream` synchronous. I had this thought a while back, The main problem with it right now is that the `verifyCallback` in `Polykey` is async.

So that needs looking into.

**Comment by CMCDragonkai** [comment]
I had a look at keys utils.

The relevant functions are

* `certNodeSigned`
* `certSignedBy`

The reason it's async is due to the x509 library, and yes it does use the webcrypto subtle.

I forgot about this cause asymmetric can verify pub keys completely synchronously.

I think it's due to the x509 structure... it is built on top of webcrypto, and because webcrypto is async, then the x509 library is async.

I remember we have a long term issue to eventually replace webcrypto with libsodium... but libsodium doesn't have all the relevant algorithms, it has a much smaller subset. Like there's no RSA support, and no ECDSA support.

It is possible to verify the certificate entirely synchronously but it would necessitate building our own x509 library based on top of libsodium, and it would also limit the key types we can support, in fact we would probably only support the Ed25519 keys...

So yes practically right now we will need to keep using x509 and thus the verify callback will need to be asynchronous, which means we bring back asynchronicity... but to `send` call which makes `recv` call async, and we can bring back the single lock to the `recv` call since sends don't really need to be mutually exclusive.

**Comment by tegefaulkes** [comment]
I added a simple bench that tests sending 1KiB messages trough just quiche and a simple runtime using a promise and loops. 

On my laptop I was getting about 2400 ops/s which is still abysmally slow. 

It's possible that since we're using erros for control flow that could significantly be reducing the performance. Anything where we need to catch a `Done` error would be generating a stack. Generaly logic flow using try/catch is pretty slow.

So moving forward I'm updating the native code to return null in the case of `Done`.



But in some cases such as `streamShutdown` don't return anything. In this case do we return `undefined` | `null`?

**Comment by CMCDragonkai** [comment]
Yes `undefined | null` in the case of `streamShutdown`.

**Comment by tegefaulkes** [comment]
OK, some new observations.

JUST doing a send loop with no other work. That is, calling `connection.send()` until it throws done over and over again results in 42000 ops/sec

Doing the same thing but with send returning null instead of throwing results in 270,000-ish ops/s

Doing the full simple runtime test again results in 3,300 ops/s. So there is another minor improvement but not enough.

**Comment by CMCDragonkai** [comment]
So 3300 is still native quiche without the rest of the runtime. That's still quite slow.

1. There could be other exceptions we want to turn into a regular value. If that's the case, we might completely change from throwing exceptions to always returning `| ErrorMessage` where `ErrorMessage` is just a special object with a string (to distinguish from regular strings) in case some functions return just strings.
2. Can you trace which of the functions is the slowest whether connection send/recv or stream write/read?

I also remember changing the per stream buffer size and it had no effect on the performance. I don't get that, could it be that the way we are buffering up the stream is incorrect?

**Comment by CMCDragonkai** [comment]
Regarding `1.` that should only be an issue if it is a regular thing as part of stream writes and reads. Otherwise it shouldn't be that big of a problem. Perhaps log out whenever an error is being created.

Regarding `2.` if we find a set of FFI functions that is in fact the slow ones. It's possible that something I'm doing inside rust is slow. Specifically the conversion of rust types to JS types using the `napi-rs` bridge. We can identify which of these is slow, and rewrite those operations.

**Comment by CMCDragonkai** [comment]
I'm adding task 7. and I'm going to bring back asynchronicity for `recv` and `send` due to `verifyCallback`. @amydevs this means your `verifyCallback` has to be asynchronous too. Beware of integrating this into the https/tls/wss protocol.

**Comment by tegefaulkes** [comment]
Looking into it more all the components are reasonably fast. But having the simple runtime doing any work significantly slows it down.

I'll check if there's an issue with the simple runtime.

**Comment by CMCDragonkai** [comment]
@tegefaulkes in the future you can directly run benchmarks without running `npm run bench`:

```
npm run ts-node -- ./benches/suites/buffers/buffer_allocation.ts
npm run ts-node -- ./benches/suites/streams/stream_1KiB.ts
```

So you don't need to stub it out.

**Comment by CMCDragonkai** [comment]
Asynchronicity is back in. Now for some robustness testing.

**Comment by tegefaulkes** [comment]
Ok, so doing the minimial amount of work  or clientSend, client sends, process streams, server sends we get about the same amount of ops of 4000 ops/s.

Here is the break down. Its a bit by the seat of my pants. Each comment is a step that shows the ops for doing everything before that point. The results are total time units to that point, difference between this point and last point, percentage total of all time.

```ts
   // Doing nothing - 12 896 010 ops/s, ±1.05%
        clientConn.streamSend(0, data1KiB, false);
        // Just passing data to `streamSend` - 451 088 ops/s, ±1.22% | 2.22 ,, 0.88%
        while(true) {
          const result = clientConn.send(dataBuffer);
          if (result === null) break;
          // Doing clientConn.send inside loop -  89 343 ops/s, ±0.91% | 11.2, 9, 3.6%
        const [serverSendLength, sendInfo] = result;
          serverConn.recv(dataBuffer.subarray(0, serverSendLength), {
            to: sendInfo.to,
            from: sendInfo.from,
          });
          // Passing data to serverConn.recv - 82 360 ops/s, ±1.45% | 12.2, 1, 0.4%
        }
        for (const streamId of serverConn.readable()){
          // Just iterating readable - 17 924 ops/s, ±6.38% | 55.6, 43.4, 17.4% (spot check);
          while(true) {
            // read and ditch information
            if (serverConn.streamRecv(0, clientBuf) === null) break;
            // Checking streamRecv inside loop - 21 113 ops/s, ±5.68% | 47.6, 35.4, 14.2%
          }
        }
        while(true) {
          const result = serverConn.send(dataBuffer);
          if (result === null) break;
          // Doing serverConn.send inside loop - 19 118 ops/s, ±3.26% | 52.6, 5.0, 2.0%
          const [serverSendLength, sendInfo] = result;
          clientConn.recv(dataBuffer.subarray(0, serverSendLength), {
            to: sendInfo.to,
            from: sendInfo.from,
          });
          // Passing data to clientConn.recv - 3 871 ops/s, ±0.88% | 250, 197.4, 79.0%
        }
```

So most of the work done is just processing the data in quiche. We can see the worst points are the readable iterator and the `clientConn.recv` which seems really weird.

**Comment by CMCDragonkai** [comment]
@amydevs latest fix 4d79d9e89fe5577be090fb9bf96ff026e2e2ee82 is useful for js-ws, consider your parser for the stream codes if you are using regex to ensure you limit to a maximum of 16 digits.

16 digits is due to the largest JS integer that it can represent. QUIC should in fact be limiting the size of such numbers... to `u64` inside rust, but I can only see strings anyway.

**Comment by CMCDragonkai** [comment]
On the native code, the `recv` call on the connection might be doing an expensive conversion of the metadata to `SocketAddr`. Because I'm passing a host and post pair. Where the `host` is a string.

I suspect it might think that the string my be a hostname and doing some sort of DNS resolution.

```
impl TryFrom<HostPort> for SocketAddr {
  type Error = io::Error;
  fn try_from(host: HostPort) -> io::Result<Self> {
    (host.host, host.port).to_socket_addrs()?.next().ok_or(
      io::Error::new(
        io::ErrorKind::Other,
        "Could not convert host to socket address"
      )
    )
  }
}
```

image

Not only that, the internal docs say that could block the thread when being called. That sounds like a DNS resolution.

**Comment by CMCDragonkai** [comment]
Possible replacement:

```
use std::net::{SocketAddr, Ipv4Addr, Ipv6Addr};
use std::convert::TryFrom;
use std::io;

struct HostPort {
    host: String,
    port: u16,
}

impl TryFrom<HostPort> for SocketAddr {
    type Error = io::Error;

    fn try_from(host: HostPort) -> io::Result<Self> {
        if let Ok(ipv4) = host.host.parse::<Ipv4Addr>() {
            return Ok(SocketAddr::new(ipv4.into(), host.port));
        }

        if let Ok(ipv6) = host.host.parse::<Ipv6Addr>() {
            return Ok(SocketAddr::new(ipv6.into(), host.port));
        }

        Err(io::Error::new(
            io::ErrorKind::Other,
            "Could not convert host to socket address",
        ))
    }
}
```

**Comment by tegefaulkes** [comment]
Testing just the  RecvInfo part of recv in a separate function results in 266 698 ops/s, ±2.34% It's about the same for the new and old code

**Comment by CMCDragonkai** [comment]
One of the main issues debugging things here is to ensure you're catching `uncaughtException` and `unhandledPromiseRejection`.

We allow these to occur for "software errors", but it can be quite confusing to understand where they happened.

When testing (not-in-jest cause it might not work there).

You have to put:

```
process.on('uncaughtException', (err, origin) => {
  console.log('Caught exception:', err);
  console.log('Exception origin:', origin);
  // Custom logic can be added here as well
});
```

Otherwise when running in ts-node, it shows up like this very confusingly:

```
/home/cmcdragonkai/Projects/js-quic/node_modules/@cspotcode/source-map-support/source-map-support.js:681
  var match = /\n    at [^(]+ \((.*):(\d+):(\d+)\)/.exec(error.stack);
                                                               ^

TypeError: Cannot read properties of undefined (reading 'stack')
    at getErrorSource (/home/cmcdragonkai/Projects/js-quic/node_modules/@cspotcode/source-map-support/source-map-support.js:681:64)
    at printFatalErrorUponExit (/home/cmcdragonkai/Projects/js-quic/node_modules/@cspotcode/source-map-support/source-map-support.js:714:16)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/cmcdragonkai/Projects/js-quic/node_modules/@cspotcode/source-map-support/source-map-support.js:753:9)
    at process.exit (node:internal/process/per_thread:193:15)
    at process.emit.sharedData.processEmitHook.installedValue [as emit] (/home/cmcdragonkai/Projects/js-quic/node_modules/@cspotcode/source-map-support/source-map-support.js:750:17)
    at process._fatalException (node:internal/process/execution:159:25)
```

Pretty sure that's an upstream bug but we are going to switch to tsx later when ESM migration occurs.

**Comment by CMCDragonkai** [comment]
A few tips for dealing with this:

* https://stackoverflow.com/questions/51105622/how-to-ensure-jest-fails-on-unhandledrejection
* https://github.com/jestjs/jest/issues/10784
* https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode
* https://nodejs.org/api/cli.html#--report-uncaught-exception
* https://nodejs.org/api/cli.html#--trace-uncaught

Once you go evented, this can be quite annoying. Primarily due to the our `Evented` not having a default event catcher that can make it easier to debug this...

I'm thinking maybe our `Evented` should in fact have something that catches the handler exceptions by default whether by rejection or not, and then subsequently report that error in a nicer way. Can be made more obvious.

**Comment by tegefaulkes** [comment]
Results from the basic rust benchmarking.

This is based off of the bench that just does a streamSend, forward packets, process streams, reverse packets.

```
for 200_000 loops
total elapsed 13210

send elapsed 625 4%
server send elapsed 1808 13%
client recv elapsed 3753 28%
stream elapsed 672 5%
client send elapsed 2597 19%
server recv elapsed 2832 21%
```

As we can see, the send and recv methods takes up most of the time. I think this is expected because this is where most of the processing will happen in quiche.

I think we've exhausted the amount of scrutiny this deserves right now. Any more optimisation can come later, I think it's fast enough for our needs right now.

**Comment by CMCDragonkai** [comment]
What does 13210 and the percentages mean?

**Comment by tegefaulkes** [comment]
Ok, so i've moved the example code outside of a test harness and into an example file. It's now in `./exampes/test_example`. It can be run independently by doing `cargo run --example test_example`. I'll push this up in a moment.

As for running flamegraph, there's some setup involved. 

1.  You need `perf` installed. in nix that's installed with `linuxPackages_latest.perf`. 
2. Install flamegraph with `

**Comment by tegefaulkes** [comment]
The SVG of the flamegraph

flamegraph

**Comment by tegefaulkes** [comment]
We've discovered that the difference in speed is due to the rust code being optimised which makes sense.  So the performance results currently look like this.

```
Optimised rust code is 250000 iterations per second
Optimised quiche code is 35000 ops per second
Optimised quic only 1896
```

We can conclude now that the quiche rust library isn't the problem here. We need to look into optimisations of the quic and FFI.

Likely the biggest optimisation we can do is process any `send` or `recv` calls in a separate thread in the rust layer only. But that would mean a major structural change to the quic API. I'm not sure we could use the node socket in that case.

**Comment by CMCDragonkai** [comment]
> We've discovered that the difference in speed is due to the rust code being optimised which makes sense. So the performance results currently look like this.
> 
> ```
> Optimised rust code is 250000 iterations per second
> Optimised quiche code is 35000 ops per second
> Optimised quic only 1896
> ```
> 
> We can conclude now that the quiche rust library isn't the problem here. We need to look into optimisations of the quic and FFI.
> 
> Likely the biggest optimisation we can do is process any `send` or `recv` calls in a separate thread in the rust layer only. But that would mean a major structural change to the quic API. I'm not sure we could use the node socket in that case.

We could still use the socket. We just have to use a shared array buffer and have all quiche calls run in a separate thread reading/writing to the shared array buffer.

Such threading could be done at the JS-level using js-workers but last I benched it, it wasn't worth it unless the call took longer than 0.5 of second or something like that.

So any threading would have be done at the native side at the ffi layer using Napi-rs threading facilities to achieve this. @amydevs knows more about this but it would not be a priority atm.

**Comment by CMCDragonkai** [comment]
What does the colours on the flame graph mean btw?

Also I think I remember one can process multiple quic packets in recv.

1 dgram is 1 quic packet. 1 quic packet is multiple quic frames.

But I think the quiche native examples actually take potentially multiple quic packets (multiple dgrams) in one go.

Which would mean a sort of unacked buffer...

Nodejs dispatches event when every dgram arrives, we could potentially buffer it up to execute if multiple dgrams arrive to coalesce.

**Comment by tegefaulkes** [comment]
From what I've seen, `quiche` doesn't combine multiple frames into a single packet.

File: src/QUICSocket.ts [hunk 9]
```diff
@@ -79,71 +119,107 @@ class QUICSocket extends EventTarget {
...
+            })
+          );
+          this.dispatchEvent(
+            new events.EventQUICSocketClose()
+          );
+          return;
+        }
+
+        // Software error - throw upwards
+        throw e;
```
Comment (tegefaulkes) [inline src/QUICSocket.ts:196]: If the server connection rejects the client TLS with custom TLS, the `acceptConnection` throws `ErrorQUICServerNewConnection: Failed to start accepted connection`.  In fact, all connection start errors are rethown as `ErrorQUICServerNewConnection: Failed to start accepted connection`. In this case this error should be ignored here as it's a recoverable error from the server and socket perspective.

Comment (CMCDragonkai) [reply src/QUICSocket.ts:196]: The `checkError` checks recursively.

**Comment by CMCDragonkai** [comment]
> From what I've seen, `quiche` doesn't combine multiple frames into a single packet.

Either way, the rust native example is potentially reading multiple dgrams in one go.

That could one way to optimise the QUIC code.

**Comment by CMCDragonkai** [comment]
image

**Comment by CMCDragonkai** [comment]
Going to bring in https://github.com/MatrixAI/js-events/pull/13 to help find it. Primarily should confirm that unhandled/uncaught isn't from one of the event handlers. But alternatively it could be from the timer cancellation.

File: Cargo.toml [hunk 10]
```diff
@@ -16,6 +16,9 @@ serde = { version = "1.0", features = ["derive"] }
 napi-derive = { version = "2", default-features = false, features = ["strict", "compat-mode"] }
 quiche = { version = "0.17.1", features = ["boringssl-boring-crate", "boringssl-vendored"] }
 boring = "2.1.0"
+# FIXME: temp for testing
+log = { version = "0.4", features = ["std"] }
+ring = "0.16"
```
Comment (CMCDragonkai) [inline Cargo.toml:21]: What's this for?

**Comment by CMCDragonkai** [comment]
It was this commit [a06e505](https://github.com/MatrixAI/js-quic/pull/53/commits/a06e505bae4c2731bcc142326fd73ac9cc0127ae). When I updated the async-init and js-events, that the uncaught exception became `null` instead of `undefined`.

Which tells me... that perhaps it has something to do with the event dispatches or async-init.

**Comment by CMCDragonkai** [comment]
Ok the new `EventError` is actually capturing it now.

The `evt.detail` is in fact `null` now.

And the domain that is thrown on is `QUICConnection` on the server side.

But it's hard to know what is actually doing this.

And the reason why the `e` became `null` is because when you instantiate a new event with `detail` set to `undefined`, the `CustomEvent` defaults it to `null`. This can be a bit confusing as you cannot really set the `detail` to be `undefined`. It's not apparent in the types however...

Anyway I found it finally by tracing it through the `EventError`.

It's actually occurring inside the `test.ts` event listener for the stream.

That's important to be careful about. If you register and event listener that could throw, then any thrown exception can become an uncaught exception which will go to `EventError` first!

Again it is quite dangerous to attach event handlers without catching them! Especially given that the user can attach their own event listeners onto the object.

Now the location of this `undefined` which then became a `null` detail. (I wonder if I should override in the `AbstractError` so that `undefined` stays `undefined` instead of converting to `null`.

**Comment by CMCDragonkai** [comment]
Found it...

Reading out of the stream results in a thrown error of `undefined` because, inside `QUICStream` we get `this.readableController.cancel()` occurring inside `readableCancel`.

This is occurring due to `QUICStream.destroy`. Which is called by `QUICConnection.stop`.

It doesn't give it a reason. The `reason` is `undefined` here.

This is because it is forcing the destruction... because `force` is now the default anyway.

Since we cancelling the `QUICStream` without any reason... that's why we get `undefined`.

Originally without `EventError` this immediately became an uncaught exception that is `undefined` because it was `test.ts` own handler... this can be very confusing if an exception occurs due the user providing their own handler and throwing up an exception that results in an uncaught exception... it makes us think that it's due to our own domain handlers, when in reality it's due to a user registered handler.

Some solutions here:

1. We should override `AbstractError` is that when `detail` is `undefined`, it stays `undefined` instead of being converted to `null`. This deviates from `CustomError` behaviour... and the type system can technically accept this... since it is `T` type. This would make it less confusing to change the `undefined` exception to a `null` exception when querying it from `EventError`.
2. We should have a reason for destroying the `QUICStream` from the `QUICConnection`. It will be very confusing that if you're trying to read something from `QUICStream` like `for await (const _ of stream.readable)` and getting an `undefined` exception because the `QUICConnection` ended up force cancelling the `QUICStream`.
3. Maybe `js-events` needs a way to differentiate between internal errors from internal event handlers and external errors from externally injected event handlers... Not sure.

**Comment by CMCDragonkai** [comment]
To achieve `2.` properly it seems that we have 2 sources of potential reasons.

1. For normal calls to `QUICConnection.stop`, we should derive the reason directly from `applicationError`, `errorMessage` and `errorCode`.
2. For handling close events (due to error events), we have no way of acquiring any error reason, because it was already reported by the error event. It might a better idea to instead get the error handler to dispatch the close event and pass the error details.

Actually for `2.` this is already possible because we do have the information in the `EventQUICConnectionClose.detail`.

However this is not the same as the exception object that is being given to the `EventQUICConnectionError.detail`.

So if we do end up calling `stop` from `2.` even if we had access to the original exception, there's no way to pass it to the `stop` call unless the `stop` method also received the exception object, which atm, it does not because it just takes `applicationError`, `errorCode`, `errorMessage`.

File: Cargo.toml (hunk 10 above)
Comment (tegefaulkes) [reply Cargo.toml:21]: It's used by the example code in `./examples/test_example.rs`. I think we can remove log but ring is needed to generate the token. But maybe we can stub that out as well.

File: src/QUICSocket.ts (hunk 9 above)
Comment (tegefaulkes) [reply src/QUICSocket.ts:196]: Sure, but `ErrorQUICConnectionStartTimeout` is not the only error we want to ignore here. There's timeout from `maxIdleTimeout`, abortion, TLS failure, etc etc..

**Comment by tegefaulkes** [comment]
If the `QUICStream.destroy()` reason is optional, i'd suggest having a default for it. Something like ` ErrorQUICStreamDestroying`. Some for the `cancel()` method with something like `ErrorQUICStreamCancelled`. 

If we're propagating the reason downwards we can see where it was triggered if a default was used. Cancelling will have the cancelled reason, stream destruction will have the destroyed reason. stopping the server can propagate it's reason down as well.

**Comment by CMCDragonkai** [comment]
> If the `QUICStream.destroy()` reason is optional, i'd suggest having a default for it. Something like ` ErrorQUICStreamDestroying`. Some for the `cancel()` method with something like `ErrorQUICStreamCancelled`.
> 
> If we're propagating the reason downwards we can see where it was triggered if a default was used. Cancelling will have the cancelled reason, stream destruction will have the destroyed reason. stopping the server can propagate it's reason down as well.

Was in the middle of that last night.

File: src/QUICSocket.ts (hunk 9 above)
Comment (CMCDragonkai) [reply src/QUICSocket.ts:196]: Right so we should make a list or just check for new connection failure in general?

File: tests/QUICServer.test.ts
Comment (tegefaulkes) [inline tests/QUICServer.test.ts:1]: The `QUICServer` does ` const address = utils.buildAddress(this.socket.host, this.socket.port);` in the `stop` method. This throws if the `QUICSocket` has already stopped. So if the `QUICSocket` stops first and triggers the `QUICServer` to stop we will run into this error.

I checked the `QUICClient.destroy()` method and it's just not creating the `address` and using it in the logging messages. So what ever we do need to be the same betweent he client and server.

**Comment by tegefaulkes** [comment]
The `listen on IPv4 mapped IPv6` test in `QUICServer.test.ts` is holding the process open. I'm not sure why since the socket is being stopped in this case.

**Comment by tegefaulkes** [comment]
Previously a `QUICStream` would throw whatever `codeToReason` returned if it had a quiche stream error. Or it would throw the reason provided by `writable.cancel` or `readable.abort`. Is that still the expectation?

Now it throws `ErrorQUICStreamPeerRead` for the readable.

I think that the streams should be throwing the exact error that is provided by `codeToReason` or the reason for `abort` or `cancel`. The Errors that are dispatched should be wrapped with the `ErrorQUICStreamPeerRead` style errors however.

**Comment by CMCDragonkai** [comment]
> To achieve `2.` properly it seems that we have 2 sources of potential reasons.
> 
> 1. For normal calls to `QUICConnection.stop`, we should derive the reason directly from `applicationError`, `errorMessage` and `errorCode`.
> 2. For handling close events (due to error events), we have no way of acquiring any error reason, because it was already reported by the error event. It might a better idea to instead get the error handler to dispatch the close event and pass the error details.
> 
> Actually for `2.` this is already possible because we do have the information in the `EventQUICConnectionClose.detail`.
> 
> However this is not the same as the exception object that is being given to the `EventQUICConnectionError.detail`.
> 
> So if we do end up calling `stop` from `2.` even if we had access to the original exception, there's no way to pass it to the `stop` call unless the `stop` method also received the exception object, which atm, it does not because it just takes `applicationError`, `errorCode`, `errorMessage`.
> 
> I think it is necessary to close before attempting to destroy the streams.
> 
> Need to fix this up soon.

js-events 3.2.0 is now defaulting to `undefined`. There's no way to force that `detail` must be supplied if the `T` is specialised. That's cause we cannot do runtime operations dependent on type changes. The only way is to overload the `AbstractError` with a custom `constructor` that forces the `detail` to be supplied. Generally speaking this is the appropriate thing to do anyway if you want enforce it, but it's just a bit of extra boilerplate.

**Comment by CMCDragonkai** [comment]
Will be updating to `1.9.3` of `js-async-init` and `3.2.0` of `js-events` together here to get the new event `detail` behavior.

File: src/QUICConnection.ts [hunk 11]
```diff
@@ -162,159 +146,115 @@ class QUICConnection extends EventTarget {
...
+   * Whenever there is a send event on a quic stream
+   * We will asynchronously proceed with a `this.send` call
+   * This also allows us to deal with failures here if it happens
+   */
+  protected handleEventQUICStreamSend = async () => {
+    // Failure of send is both a caller error and domain error
+    // In this case we can ignore the caller error, since the domain error will be handled
+    // by the QUICConnection error handlers
+    await this.send();
+  };
```
Comment (tegefaulkes) [inline src/QUICConnection.ts:235]: Very weird error here. the `await this.send()` call is throwing `ErrorQUICConnectionNotRunning`.  It's weird since the connection has not actually stopped yet.

I can see in the logs that the connection stops RIGHT after this error. So it's likely a race condition there where the connection is stopping before logging out the stopping message.

The weird thing is, the `send()` method is allowed to run when stopping. So maybe there's a bug with `async-init` that this is not working properly?

**Comment by CMCDragonkai** [comment]
> To achieve `2.` properly it seems that we have 2 sources of potential reasons.
> 
> 1. For normal calls to `QUICConnection.stop`, we should derive the reason directly from `applicationError`, `errorMessage` and `errorCode`.
> 2. For handling close events (due to error events), we have no way of acquiring any error reason, because it was already reported by the error event. It might a better idea to instead get the error handler to dispatch the close event and pass the error details.
> 
> Actually for `2.` this is already possible because we do have the information in the `EventQUICConnectionClose.detail`.
> 
> However this is not the same as the exception object that is being given to the `EventQUICConnectionError.detail`.
> 
> So if we do end up calling `stop` from `2.` even if we had access to the original exception, there's no way to pass it to the `stop` call unless the `stop` method also received the exception object, which atm, it does not because it just takes `applicationError`, `errorCode`, `errorMessage`.
> 
> I think it is necessary to close before attempting to destroy the streams.
> 
> Need to fix this up soon.

This is now done for `QUICConnection`.

Because this chaining of error to close works for `QUICConnection`, I'm going to try to apply this to `QUICStream`, `QUICClient` and `QUICServer` so that it is consistent behaviour.

@amydevs will need to follow this in js-ws.

File: Cargo.toml (hunk 10 above)
Comment (CMCDragonkai) [reply Cargo.toml:21]: I think the examples should be self contained into a subdirectory and shouldn't be part of the main scaffolding.

**Comment by CMCDragonkai** [comment]
> image
> 
> https://queue.acm.org/detail.cfm?id=2927301

Idea for optimising the QUIC side. Increase the UDP socket buffer size. @tegefaulkes said it would result in dropping the newest data if there's not enough buffer size to hold the queued up dgrams. If the default socket buffer size is too small, this can cause quiche to repeat dropped data. Usually not a problem if the application reading out from the socket is a tight loop as in the rust native example, but it is a problem for js-quic because the JS code is quite heavy on the `handleSocketMessage`.

https://stackoverflow.com/questions/27867428/node-js-receiving-too-many-udp-messages-at-a-time-losing-them

Another idea is to introduce a "socket window size" buffer which would means the `handleSocketMessage` would accumulate dgrams into an application buffer. And then send it all to `recv`. However the problem here is that each dgram which is 1 QUIC packet may be for a different connection, which would necessitate creating per-connection window size. However this is already being done internally inside quiche. And it would introduce significant complexity. So not doing this.

In the future it would be possible to do native threading so that quic connection recv/send occurs in a separate thread entirely thus not blocking the `handleSocketMessage` calls on the main thread. Remember when decryption/encryption is blocking the main thread, nothing else in nodejs is running and thus it's not reading data out of the UDP socket.

Thus we should try to increase the socket buffer size and see if that helps. The default connection window size is already 24 MiB.

**Comment by tegefaulkes** [comment]
I still need to fix the bug where the `QUICStream` is not properly responding to a readable stream cancellation on the writable side. 

This is triggered by both readable streams being cancelled concurrently. This leads to the writable stream entering a invalid state before being written to. `streamSend` returns null in this case which is odd, I'd expect the invalid state error here. Ultimately the writable stream deadlocks and never cleans up.

**Comment by tegefaulkes** [comment]
The temp fixes are in order...

1. graceful fail fix was addressing an issue where the `QUICSocket` wasn't properly handling a connection failing while starting in all cases.
2. Socket stops before server does. This caused an socket not running error when the server was stopping. It was trying to get the socket's host and port for logging purposes. I removed the address from the logging message.
3. streams throwing original errors. In most cases, when the streams errored/cancelled/aborted, they were throwing a wrapped error rather than the original one causing the stream to error.

File: src/QUICServer.ts [hunk 12]
```diff
@@ -346,8 +346,7 @@ class QUICServer {
           force?: boolean;
         } = {},
   ) {
-    const address = utils.buildAddress(this.socket.host, this.socket.port);
-    this.logger.info(`Stop ${this.constructor.name} on ${address}`);
+    this.logger.info(`Stop ${this.constructor.name}`);
```
Comment (CMCDragonkai) [inline src/QUICServer.ts]: I think this should still exist... but as you said, if the socket were stopped prior to the server, then it cannot access the `host` and `port` parameters anymore.

We know that this would actually be considered a runtime error.

So instead of doing this, what we can do is check if the socket is running, and if it is, get the `address` and if it isn't running, don't use the address.

The same issue has to be applied on `QUICClient` too as it has the same problem.

File: src/QUICStream.ts
Comment (CMCDragonkai) [inline src/QUICStream.ts:1]: Yes so this is correct and actually the `reason` was being used in `readableCancel`, so this aligns behaviour properly.

File: src/QUICServer.ts (hunk 12 above)
Comment (CMCDragonkai) [reply src/QUICServer.ts]: Fixed this now in d5f6519ed01f7e0aa87bd0a9090a0ab299e21451

File: src/QUICConnection.ts (hunk 11 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Can you confirm this?

File: tests/QUICServer.test.ts
Comment (CMCDragonkai) [reply tests/QUICServer.test.ts:1]: Done d5f6519ed01f7e0aa87bd0a9090a0ab299e21451

**Comment by CMCDragonkai** [comment]
Ok finally everything is using the new error to close flow. @amydevs have a look at the current code. Especially do note the relationship between `QUICClient` and `QUICConnection`.

Notice that `test.ts` now runs properly and in fact the `QUICClient` is finally destroyed.

@tegefaulkes take note if there's any issues that pop up with the new changes.

**Comment by tegefaulkes** [comment]
I see you changed the `port` and `host` getters on the client. We now have `localHost`, `host`, `localPort`, `port`. The meaning of these seem inconsistent now, the `client.host` refers to the peer host. but the `server.host` refers to the local host.  I think we should change the `client.host` to `client.peerHost` and the `server.host` becomes `server.localHost` just to avoid confusion.

File: src/QUICClient.ts [hunk 13]
```diff
@@ -223,233 +212,405 @@ class QUICClient extends EventTarget {
...
+  /**
+   * This must be attached multiple times.
+   */
+  protected handleEventQUICConnectionSend = async (evt: events.EventQUICConnectionSend) => {
+    try {
+      await this.socket.send_(
+        evt.detail.msg,
+        evt.detail.port,
+        evt.detail.address,
+      );
```
Comment (tegefaulkes) [inline src/QUICClient.ts:461]: New race condition. If the socket stops first then this is getting triggered by the connection stopping.

```
INFO:QUICClient Test.QUICServer.QUICConnection 83668673c4c533d4fb56f9511ce7fb9ad50cf870:Started QUICConnection
INFO:QUICClient Test.QUICClient.QUICSocket:Stop QUICSocket on 127.0.0.1:40591
INFO:QUICClient Test.QUICClient.QUICSocket:Stopped QUICSocket on 127.0.0.1:40591
ERROR:QUICClient Test.QUICClient:ErrorQUICClientSocketNotRunning: QUIC Client cannot be created with an unstarted shared QUIC socket - 
INFO:QUICClient Test.QUICClient.QUICConnection ba5d0b60f693f63ab67d1cc579d43fe70d310a04:Stop QUICConnection
ERROR:QUICClient Test.QUICClient.QUICConnection ba5d0b60f693f63ab67d1cc579d43fe70d310a04:ErrorQUICConnectionLocal: QUIC Connection local error - Locally closed with application code 1
  ERROR:QUICClient Test.QUICClient:ErrorQUICClientInternal: QUIC Client internal error - Failed to send data on the QUICSocket
console.error
    ErrorQUICSocketNotRunning: 
        at constructor_.send_ (/home/faulkes/matrixcode/polykey/js-quic/src/QUICClient.ts:457:25)
        at EventTarget.handler (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:121:35)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
        at EventTarget.dispatchEvent (node:internal/event_target:713:26)
        at constructor_.dispatchEvent (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:285:43)
        at constructor_.dispatchEvent (/home/faulkes/matrixcode/polykey/js-quic/src/QUICConnection.ts:865:12)
        at constructor_.send (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/async-init/src/StartStop.ts:141:20)
        at constructor_.send [as handleEventQUICConnectionClose] (/home/faulkes/matrixcode/polykey/js-quic/src/QUICConnection.ts:239:18)
        at EventTarget.handler (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:121:35)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
        at EventTarget.dispatchEvent (node:internal/event_target:713:26)
        at constructor_.dispatchEvent (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:285:43)
        at constructor_.dispatchEvent [as handleEventQUICConnectionError] (/home/faulkes/matrixcode/polykey/js-quic/src/QUICConnection.ts:213:10)
        at EventTarget.handler (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:121:35)
        at EventTarget.[nodejs.internal.kHybridDispatch] (node:internal/event_target:778:20)
        at EventTarget.dispatchEvent (node:internal/event_target:713:26)
        at constructor_.dispatchEvent (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:285:43)
        at constructor_.dispatchEvent (/home/faulkes/matrixcode/polykey/js-quic/src/QUICConnection.ts:586:12)
        at /home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/async-init/src/StartStop.ts:99:36
        at /home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/async-locks/src/RWLockWriter.ts:252:64
        at withF (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/resources/src/utils.ts:24:18)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at constructor_.handleEventQUICClientClose (/home/faulkes/matrixcode/polykey/js-quic/src/QUICClient.ts:372:5)
        at EventTarget.handler (/home/faulkes/matrixcode/polykey/js-quic/node_modules/@matrixai/events/src/Evented.ts:136:19) {
      data: {},
      cause: undefined,
      timestamp: 2023-09-21T00:26:03.493Z
    }

      461 |       );
      462 |     } catch (e) {
    > 463 |       console.error(e);
          |               ^
      464 |       // Caller error means a domain error here
      465 |       const e_ = new errors.ErrorQUICClientInternal(
      466 |         'Failed to send data on the QUICSocket',

      at constructor_.error (src/QUICClient.ts:463:15)
      at EventTarget.handler (node_modules/@matrixai/events/src/Evented.ts:136:19)
```

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: The condition we're looking for is, if the stream is readable AND finished then there is an error to be read and it needs to be cleaned up. 

Under normal conditions, the stream only becomes finished when all data is read out of quiche for that stream including the finish flag being true. The only time the stream is finished with existing data to be read if there was an error on the stream and all buffered data was dropped.

**Comment by tegefaulkes** [comment]
Pushed temp fix for handling write stream errors properly. Still needs review.

Readable stream needs the same treatment, currently it doesn't respond to readable stream errors unless it's actively pulling.

File: src/QUICClient.ts (hunk 13 above)
Comment (CMCDragonkai) [reply src/QUICClient.ts:461]: That's cause it's running asynchronously. If the socket is stopped, don't run it. Do a check condition on the running symbol.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (CMCDragonkai) [reply src/QUICStream.ts:1]: Is this the writable problem you mentioned yesterday?

**Comment by CMCDragonkai** [comment]
> Pushed temp fix for handling write stream errors properly. Still needs review.
> 
> Readable stream needs the same treatment, currently it doesn't respond to readable stream errors unless it's actively pulling.

I'm thinking maybe the read/write functions in QUICStream should centralise these cases?

**Comment by tegefaulkes** [comment]
I'm not sure what you mean. But yes, the read/write functions are where we need to check the stream states to be proactive about handling them.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: Yes.

File: src/QUICClient.ts (hunk 13 above)
Comment (tegefaulkes) [reply src/QUICClient.ts:461]: Do we want to check in the send handler for the server/client or in the stop method before dispatching send in connection? The streams could also be triggering their own send events.

Comment (CMCDragonkai) [reply src/QUICClient.ts:461]: I think it should in the event handler. Try it and see what happens?

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (CMCDragonkai) [reply src/QUICStream.ts:1]: How would you know the stream errored if there is still stream data buffered up?

File: src/QUICConnection.ts (hunk 11 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Will this require a check for the connection is running too? Again same issue because handling could be async.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: If data was on the quiche stream, then the stream becomes readable on the iterator and `QUICStream.read()` will be called. `conn.streamFinished()` will be true. In this case we just need to read the error from the stream with `conn.streamRecv()` to process the error.

In this case it's likely that the readable webstream will have buffered data and not be pulling. So we'll need to trigger a `QUICStream.readablePull()` or handle reading the error inside of the `QUICStream.read()` method.

If the readable webstream is awaiting more data with a promise, then that promise just needs to be resolved.

File: src/QUICClient.ts (hunk 13 above)
Comment (tegefaulkes) [reply src/QUICClient.ts:461]: I have a tempfix doing that and it's working.

Comment (CMCDragonkai) [reply src/QUICClient.ts:461]: Needs to be done for the quicstreamsend handler too

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (CMCDragonkai) [reply src/QUICStream.ts:1]: We can't trigger readable pull. That wouldn't be right. Instead a better way is to check inside `QUICStream.read()`. I'm just saying that if the readable was reset, then how would you know without reading data off the stream?

[the remark this answers is not in the document]
Comment (CMCDragonkai) [reply src/QUICStream.ts:1]: Can you peek I to the readable and check if it has been reset without reading any data?

File: src/QUICClient.ts (hunk 13 above)
Comment (CMCDragonkai) [reply src/QUICClient.ts:461]: Can you push up the fix for this and quic stream send handler and this and the above one can be resolved.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: Yeah, you can tell that it has been reset if it's readable and `connection.streamFinished(id)` returns true.
By checking if readable and finished we can conclude the following

| \| finished | not finished |
|--------|--------|--------|
| readable | A | B |
| not readable | C | D |

A.  Readable and finished means there's an error code to be processed, all buffered data was dropped.
B. Buffered data to be pulled
C. Only possible after reading the finish frame or the error code. if the writable had already ended then the stream would'd exist.
D. Stream still active but no data to be pulled.

So yes, we can tell without reading data with `streamRecv`.

File: src/QUICClient.ts (hunk 13 above)
Comment (tegefaulkes) [reply src/QUICClient.ts:463]: Fixed in `tmp: temp fix for socket send errors when socket ends first` for the server and client. the fix is also applied to the `QUICConnection` but there's still a bug with `QUICConnection.send()` pending an uptade to  `async-init` .

**Comment by tegefaulkes** [comment]
Pretty much everything in stream tests is addressed or semi-addressed. Last thing I need to do is fix the readable stream protectively responding to errors.

**Comment by tegefaulkes** [comment]
Most of the native tests are broken, they need a once over. Most of it will be due to expecting `Done` still. The concurrency tests still need a once over as well.

File: src/QUICClient.ts (hunk 13 above)
Comment (tegefaulkes) [reply src/QUICClient.ts:463]: Done

**Comment by tegefaulkes** [comment]
Concurrency test working.

Only stuff left to fix is the readable stream handling errors properly and the native tests need a minor update.

**Comment by CMCDragonkai** [comment]
> Most of the native tests are broken, they need a once over. Most of it will be due to expecting `Done` still. The concurrency tests still need a once over as well.

This is all due to `Done` exception change to returning `null`.

File: src/QUICConnection.ts (hunk 5 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Done in 5616354d15ab9e020a12b86598c842ee21d8b170

File: src/QUICConnection.ts (hunk 8 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts:1132]: This still shouldn't be necessary. Should recheck.

Comment (CMCDragonkai) [reply src/QUICConnection.ts:1132]: Going to do this below.

File: src/QUICSocket.ts (hunk 9 above)
Comment (CMCDragonkai) [reply src/QUICSocket.ts]: Done in 67c28f67555ad53ab4bd7d19cc5cdd50407cdbb0.

File: src/QUICConnection.ts (hunk 11 above)
Comment (CMCDragonkai) [reply src/QUICConnection.ts]: Fixed in fedb61c0df3dab7be0a4c72f3d7206b6d5d3a778. One diff is that `QUICConnection.send` can be done while it is stopping, but `QUICSocket.send` cannot be done if it is stopping.

**Comment by CMCDragonkai** [comment]
There are some left over reviews to fix.

For the native example scaffolding

* https://github.com/MatrixAI/js-quic/pull/53#pullrequestreview-1633370695
* https://github.com/MatrixAI/js-quic/pull/53#pullrequestreview-1633372909

For the readable stream fixes when the stream is reset:

* https://github.com/MatrixAI/js-quic/pull/53#pullrequestreview-1636738573
* @amydevs does this affect `WebSocketStream`? If you reset a websocketstream, what happens? Does a websocket stream even have the concept of a reset?

Other things:

* Native tests to be adapted to deal with `null` returns instead of `Done` exception.
* Issue for native multithreaded `recv` and `send`.

File: src/QUICConnection.ts (hunk 11 above)
Comment (tegefaulkes) [reply src/QUICConnection.ts]: This has been resolved by `@matrixai/async-init` version `^1.10.0`.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: I'm amending A, it is also possible if there the stream received the FIN flag and no data was buffered. We just need to process the fin here and end the readable.

**Comment by CMCDragonkai** [comment]
Standardise TLS between WS and QUIC: https://github.com/MatrixAI/Polykey/issues/551#issuecomment-1730732555

**Comment by CMCDragonkai** [comment]
@tegefaulkes why does QUIC not automatically check for server identity given that our generated TLS certs are not supplying "proper" X509 certs where the CN doesn't in fact match the IP address or the hostname that we are serving from?

Our generated x509 certs have neither the properly setup CN nor subject alternative name and yet it's passing when we are enabling `verifyPeer`?

**Comment by tegefaulkes** [comment]
This is weird. I looked for an option and I couldn't find it. I looked through the boring crate source code and found a `verify_hostname` which it is setting to true internally. 

https://docs.rs/boring/3.0.4/src/boring/ssl/connector.rs.html#113

As for why it's not working? No idea. Do we even specify a hostname in the certs when generating them? Is it a required field?

**Comment by CMCDragonkai** [comment]
> Standardise TLS between WS and QUIC: [MatrixAI/Polykey#551 (comment)](https://github.com/MatrixAI/Polykey/issues/551#issuecomment-1730732555)

This is now done, the native tests will need to be updated with the new `verifyCallback` as they now provide DER buffer arrays instead of PEM string arrays.

**Comment by CMCDragonkai** [comment]
> > Standardise TLS between WS and QUIC: [MatrixAI/Polykey#551 (comment)](https://github.com/MatrixAI/Polykey/issues/551#issuecomment-1730732555)
> 
> This is now done, the native tests will need to be updated with the new `verifyCallback` as they now provide DER buffer arrays instead of PEM string arrays.
> 
> The `QUICServer` also now shallow copies the config with `{...this.config}` in case the `QUICServer.updateConfig` is done.

More needs to change:

1. `QUICConnection.getLocalCertsChain`
2. `QUICConnection.getRemoteCertsChain`
3. `QUICConnection.meta`
4. `QUICConnectionMetadata`

**Comment by CMCDragonkai** [comment]
> This is weird. I looked for an option and I couldn't find it. I looked through the boring crate source code and found a `verify_hostname` which it is setting to true internally.
> 
> https://docs.rs/boring/3.0.4/src/boring/ssl/connector.rs.html#113
> 
> As for why it's not working? No idea. Do we even specify a hostname in the certs when generating them? Is it a required field?

Yes it's part of the `CN` field. It is currently set to the cert issue number, even though that's not what PK does which is to set to the public key node ID. Normally this is given by the user like `localhost`, `127.0.0.1`, `polykey.com`.

**Comment by tegefaulkes** [comment]
Found a new bug related to the last one. If we have a stream that only exist locally. e.g. we've created a new stream but haven't sent data yet. And we cancel it, we end up with a deadlocked writable stream on the peer.

When the cancel is done and the error frames are sent, the peer is creating it's stream state and closing the readable. But the writable isn't being closed. I checked and checking if the stream is writable throws the expected error. But checking AFTER processing the readable stream then it just throws `invalidState(id)` error.

It seems that the quiche stream state is being cleaned up before we're able to process the writable in this case.

I may have to check the writable inside of `read()` as well as `write()`.

**Comment by CMCDragonkai** [comment]
> > This is weird. I looked for an option and I couldn't find it. I looked through the boring crate source code and found a `verify_hostname` which it is setting to true internally.
> > https://docs.rs/boring/3.0.4/src/boring/ssl/connector.rs.html#113
> > As for why it's not working? No idea. Do we even specify a hostname in the certs when generating them? Is it a required field?
> 
> Yes it's part of the `CN` field. It is currently set to the cert issue number, even though that's not what PK does which is to set to the public key node ID. Normally this is given by the user like `localhost`, `127.0.0.1`, `polykey.com`.

So the reason for this is due to `quiche.Connection.connect` doesn't have `serverName` parameter set. It is currently set to `null`. And when it is set to null, that means the name of the server's cert isn't checked.

This should be set to the original `host` in `QUICClient`.

So when we do `await QUICClient.createQUICClient`, we pass in a `host` parameter which could be the original host name or an IP address. The hostname gets resolved to an IP. We need to use the original host whether it is the hostname of IP here.

I need to check if when disabling `verifyPeer`, that the server name is still checked. In NodeJS, the TLS module doesn't bother checking the server name if `rejectUnauthorized` is false and `checkServerIdentity` is undefined, and this behavour should be aligned. If it is different, then it's just a matter of not setting this parameter.

**Comment by tegefaulkes** [comment]
I don't think we should be internally logging error messages relating to connection events. Such as connection errors or stream errors. 

I think we should rarely log this stuff out internally. Only software errors should have error logs and only if they can't bubble upwards. 

In all other cases I think it should be up to whatever is using quic to error log these events.

**Comment by CMCDragonkai** [comment]
> I don't think we should be internally logging error messages relating to connection events. Such as connection errors or stream errors.
> 
> I think we should rarely log this stuff out internally. Only software errors should have error logs and only if they can't bubble upwards.
> 
> In all other cases I think it should be up to whatever is using quic to error log these events.

Keep the logs for now, application can filter stuff on the outside. The logging library is flexible.

**Comment by CMCDragonkai** [comment]
@tegefaulkes while fixing TLS tests you should see if we can fix the generate cert too. It should parameterise the subject and issuer names but default it to the public key node ID (similar to PK). Converting to an ID could just be a pub key 256 bit truncation.

**Comment by CMCDragonkai** [comment]
So now we still need to fix `generateCertificate`, I think the test utilities isn't doing that correctly. The `verifyPeer` option by default now does do a server name check.

I also noticed some usability issues with dual stack by default... and attempting to connect to `127.0.0.1`. Need to review this.

File: src/QUICStream.ts
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply src/QUICStream.ts:1]: This has been addressed now.

File: Cargo.toml (hunk 10 above)
Comment (tegefaulkes) [reply Cargo.toml]: Removed.

File: Cargo.toml [hunk 14]
```diff
@@ -22,3 +22,7 @@ ring = "0.16"
 
 [build-dependencies]
 napi-build = "2"
+
+# FIXME: included for flamegraph, remove later?
+[profile.release]
+debug = true
```
[the remark this answers is not in the document]
Comment (tegefaulkes) [reply Cargo.toml]: Removed.

**Comment by tegefaulkes** [comment]
I fixed up the tests based on the new verifyCallback changes. There are some tests failing in `QUICClient.test.st` due to the certs not being generated properly yet.

So all tests except 6 are passing now. They're pending the generate cert fix.

I removed the scaffolding, from the `cargo.toml` and removed their usage from the example. It wasn't needed.

What's left from the list is.
1. Fix certs generation to include hostname.
2. Test the last 4 client tests that are failing.
3. usability fixes for the socket.

**Comment by CMCDragonkai** [comment]
@tegefaulkes I think you are still using the old `testsUtils.generateConfig`. I had already changed to a new function `generateTLSConfig`. So I'm deleting the old `generateConfig`. The tests will need to be updated with the new `generateTLSConfig`.

**Comment by CMCDragonkai** [comment]
Now the `generateCertificate` is aligned with PK. So when I generate a Ed25519 cert, and use `step certificate inspect` I see something like this:

```
[nix-shell:~/Projects/js-quic]$ step certificate inspect ./leafCert.pem
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 1 (0x1)
    Signature Algorithm: Ed25519
        Issuer: CN=05dfc945668c96022c887501fa75728b03293dd60ef53cbe0d9d8f68f833ece2
        Validity
            Not Before: Sep 22 08:36:38 2023 UTC
            Not After : Sep 19 08:36:38 2033 UTC
        Subject: CN=6ea77f22c9d437346fd44f0ebf1a06f831c1e5c31915e105c4112eb7e29d5944
        Subject Public Key Info:
            Public Key Algorithm: Ed25519
                Public-Key: (32 bit)
                    69:5e:db:78:5c:1c:cf:1d:13:5a:8f:e2:2a:76:03:
                    9c:05:e7:12:2a:c3:18:b9:b7:3c:4c:58:b0:60:0e:
                    ef:4c
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Key Usage:
                Digital Signature, Content Commitment, Key Encipherment, Data Encipherment, Key Agreement, Certificate Sign, CRL Sign
            X509v3 Extended Key Usage:
                Server Authentication, Client Authentication, Code Signing, E-mail Protection, Time Stamping, OCSP Signing
            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:6ea77f22c9d437346fd44f0ebf1a06f831c1e5c31915e105c4112eb7e29d5944
                IP Address:127.0.0.1, IP Address:::1
            X509v3 Subject Key Identifier:
                B7:4A:62:DC:52:A6:E9:A2:7D:A3:63:3A:D8:33:A5:BE:8F:2E:6B:EA
    Signature Algorithm: Ed25519
         79:51:dc:ef:9c:fa:23:9f:74:22:2e:d9:b5:1a:d4:0f:1e:38:
         1b:8a:74:56:37:be:f1:bc:de:45:09:30:52:a2:2c:fe:7e:b3:
         d6:80:24:e6:9d:a6:be:db:43:7e:dc:55:10:0c:48:a6:e6:1d:
         38:19:34:be:e3:f4:d2:7a:35:0b
```

And for the CA cert:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
    Signature Algorithm: Ed25519
        Issuer: CN=05dfc945668c96022c887501fa75728b03293dd60ef53cbe0d9d8f68f833ece2
        Validity
            Not Before: Sep 22 08:36:38 2023 UTC
            Not After : Sep 19 08:36:38 2033 UTC
        Subject: CN=05dfc945668c96022c887501fa75728b03293dd60ef53cbe0d9d8f68f833ece2
        Subject Public Key Info:
            Public Key Algorithm: Ed25519
                Public-Key: (32 bit)
                    e4:f4:05:6a:ab:d8:93:b2:6c:cf:1a:9a:c0:88:63:
                    28:9f:c5:a2:6a:f8:f2:07:c7:38:52:66:42:1c:54:
                    b6:6e
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:TRUE
            X509v3 Key Usage:
                Digital Signature, Content Commitment, Key Encipherment, Data Encipherment, Key Agreement, Certificate Sign, CRL Sign
            X509v3 Extended Key Usage:
                Server Authentication, Client Authentication, Code Signing, E-mail Protection, Time Stamping, OCSP Signing
            X509v3 Subject Alternative Name:
                DNS:localhost, DNS:05dfc945668c96022c887501fa75728b03293dd60ef53cbe0d9d8f68f833ece2
                IP Address:127.0.0.1, IP Address:::1
            X509v3 Subject Key Identifier:
                3F:0C:16:CE:99:BF:92:02:91:85:57:EC:57:30:32:54:C3:5D:F4:85
    Signature Algorithm: Ed25519
         8c:e3:d2:db:07:6f:36:e3:48:dc:a3:47:67:57:ea:9d:03:ad:
         f5:66:1d:6d:28:06:0c:71:fa:28:fc:db:bd:9b:94:d6:bf:b1:
         db:d7:1a:6f:c1:dc:a8:42:78:07:51:20:91:f2:f0:f4:21:48:
         c3:78:15:8a:12:4b:28:84:61:01
```

**Comment by CMCDragonkai** [comment]
The generated certificate now I think follows properly:

1. Subject is a 256 bit hash of the SPKI buffer of the public key.
2. Issuer is always lined up with the CA. I don't think this was true before...
3. Proper SAN is done for `localhost`, 256 bit hash of SPKI buffer of the public key, and 127.0.0.1 and `::1`.

Now we can proceed to test again that server name checking actually works properly.

**Comment by CMCDragonkai** [comment]
Ok tests show that:

1. Server name check works for `localhost`, when I put `localhost` as a SAN in the certificate. (Remember that `localhost` resolves to `::1` on modern computers)
2. Server name check **does not work** for `::1` even when `::1` is in the SAN. This may be a limitation of quiche's boringssl. It might also be due to incorrectly encoding `::1` in the certificate SAN.

**Comment by CMCDragonkai** [comment]
Ok I found out that IP addresses only works if the SAN type is `dns`, not `ip`.

If I set `127.0.0.1` as the `dns` or `::1` as `dns` types, then it works fine.

I believe quiche's boringssl is strictly checking only the dns types and ignoring all the other types in the SAN check. And furthermore it doesn't understand the the equivalence between `0000:0000:0000:0000:0000:0000:0000:0001` and `::1`. So it is strict comparison on the `server_name` parameter and the CN and dns SAN properties.

So this looks like quiche's boringssl isn't entirely correct here.

**Comment by CMCDragonkai** [comment]
The `generateCertificate` is fixed now.

Note that the newly generated certs when inspected with `step certificate inspect` will show:

```
            X509v3 Subject Alternative Name:
                DNS:e4312e96caa7c6430616f3b51a2d1decded883986ad79746ad1313889843b134, DNS:localhost, DNS:127.0.0.1, DNS:::1
                IP Address:127.0.0.1, IP Address:::1
```

**Comment by CMCDragonkai** [comment]
When all tests updated should update quiche to the latest and check if it works with 0.18.

**Comment by CMCDragonkai** [comment]
Some usability improvements to be done:

1. If the socket is IPv4
   - If target is IPv4 - pass
   - If target is IPv6 - fail
   - If target is IPv4 mapped IPv6 - unwrap and pass
2. If the socket is IPv4 but uses IPv4 mapped IPv6
   - If target is IPv4 - wrap and pass
   - If target is IPv6 - fail
   - If target is IPv4 mapped IPv6 - pass
2. If the socket is IPv6
   - If target is IPv4 - fail
   - If target is IPv6 - pass
   - If target is IPv4 mapped IPv6 - fail
4. If the socket is IPv4 & IPv6 (dual stack)
   - If target is IPv4 - wrap and pass
   - If target is IPv6 - pass
   - If target is IPv4 mapped IPv6 - pass

Right now `QUICSocket` is quite strict, and so prevents most of the ones that require wrap or unwrap. We can leave it to be strict in this case... since the underlying nodejs dgram socket is strict.

However `QUICClient` doesn't have to be as strict, it can also do the automatic wrapping and unwrapping ahead of time.

One thing though... when we send back we use the address that quiche tells us. I'm not sure how quiche supports ipv4 mapped ipv6 addresses. If it doesn't behave the same as nodejs, then we are likely need to do the wrapping/unwrapping automatically during the `send` call too. I currently use `QUICSocket.send_`, and I think that's a lower level call to avoid all the overhead.

But the question is how quiche deals with being a dual stack socket, and getting a request from a ipv4 socket... this requires some tests.

**Comment by CMCDragonkai** [comment]
Usability is improved on `QUICSocket` atm. The above rules now apply, and additionally there's a check on whether you are intending to send to a wild card address, which is doable on Linux but most likely incorrect.

**Comment by CMCDragonkai** [comment]
Usability is now improved on both QUICSocket and QUICClient according to the rules above.

Futhermore, `QUICConnection` still continues to use `QUICSocket.send_` which is the alternative raw send.

This is because once a quic connection is established, it no longer matters what the hostname resolves to. We always assume the IPs are still fixed. Only new connections may attempt to resolve the hostname again. This means we can use the `remoteInfo` that is produced by `quiche::Connection::send`.

Therefore `QUICSocket.send` does some intelligent checks and should be used most of the time. But for when you know exactly that you have the right parameters and everything is resolved, proceed to use `QUICSocket.send_`.

Note that I'm not sure if there's any dual stack/ipv4 mapped ipv6 testing on QUICClient/QUICServer. That would be something you can finish up with @tegefaulkes.

**Comment by CMCDragonkai** [comment]
I've cleaned up commentary and lintfixing for everything except tests, benches and `QUICStream`.

@tegefaulkes I had a look `checkWritableClosed` and `checkReadableClosed`, but it seems significantly complex and would slow down everything during stream processing. Are you sure you're doing this most optimal way? It seems crazy to require so much checking on every read/write of a stream.

**Comment by CMCDragonkai** [comment]
Plus your stream readable/writable still has a bunch of temporary errors. I don't think this is finished?...

**Comment by tegefaulkes** [comment]
`checkWritableClosed` and `checkReadableClosed` during normal usage only does a single boolean check during normal operation. Everything else happens only of the stream in question has an error or ended.

**Comment by CMCDragonkai** [comment]
> I've cleaned up commentary and lintfixing for everything except tests, benches and `QUICStream`. For tests and benches, @tegefaulkes still require you to clean up according to changes in the `tests/utils.ts` and then final benches clean up, since I think we should be able to focus on a only a few relevant ones, and I have no idea what the `minimal` one is for.
> 
> @tegefaulkes **I had a look `checkWritableClosed` and `checkReadableClosed`, but it seems significantly complex and would slow down everything during stream processing. Are you sure you're doing this most optimal way? It seems crazy to require so much checking on every read/write of a stream.**

I've changed this up so that readable and writable streams are processed independently.

In both cases if the `QUICStream` doesn't exist, it will attempt to create the `QUICStream`. This deals with the situation where we may receive a `RESET_STREAM` or `STOP_SENDING` out of order.

Then after creating or not creating the quic stream. We always call `QUICStream.read` or `QUICStream.write` when it is readable or writable.

In `QUICStream.read`, we need to check if the stream has been cancelled with `RESET_STREAM` and error out if so. If not, it should gracefully close or not and resolve the `readableP`.

In `QUICStream.write`, we need to check if the stream has been aborted with `STOP_SENDING` and error out if so. If not, it should just resolve the `writableP`.

This should simplify the flows. The key difference here is that this is event driven from the connection. Whereas when the reader/writer is blocked or interacting with the readable/writable, that's driven by the reader/writer caller.

I've removed `QUICStream.checkReadableClosed` and `QUICStream.checkWritableClosed` then.

YMMV, need to test this.

**Comment by CMCDragonkai** [comment]
Now all tests pass except some native tests.

**Comment by CMCDragonkai** [comment]
So for benchmarks we will prebuild before running them:

```
    "bench": "npm run prebuild -- --production && rimraf ./benches/results && ts-node ./benches"
```

Note that this is similar to the new ESM style anyway:

```
    "bench": "tsc -p ./tsconfig.build.json && shx rm -rf ./benches/results && tsx ./benches/index.ts"
```

Notice we don't use `npm run build`, we always use `tsc -p` directly to avoid deleting the incremental index, this makes it faster to run benchmarks.

When `js-quic` changes to ESM, we can do:

```
    "bench": "npm run prebuild -- --production && tsc -p ./tsconfig.build.json && rimraf ./benches/results && tsx ./benches/index.ts"
```

**Comment by tegefaulkes** [comment]
Benches are fixed up.

**Comment by CMCDragonkai** [comment]
New issues created:

* https://github.com/MatrixAI/js-quic/issues/54
* https://github.com/MatrixAI/js-quic/issues/55
* https://github.com/MatrixAI/js-quic/issues/56

**Comment by CMCDragonkai** [comment]
Ok it's time to squash and merge now.

**Comment by CMCDragonkai** [comment]
Final bench results should go into the staging PR that will be created.

**Comment by CMCDragonkai** [comment]
I've reworked all the commits, the last commit still wip. But this MR is ready. We can merge now.

Also confirmed that a lazy timer indeed only changes the status lazily. So it does need to be deleted. Only non-lazy timer will synchronously change the status.
